:PROPERTIES:
:ID:       2AD3D09B-9FD6-4131-B497-4DE819E25BA7
:END:
#+title: QT4 CG Meeting 010 Agenda 2022-11-08
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

* Agenda
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: agenda
:END:

This meeting will be hosted on Zoom at 16:00GMT (17:00CET, 11:00EST).

See the [[https://qt4cg.org/meeting/logistics.html][meeting logistics]] page for details.

Reminder: several regular members of the CG will be attending
Declarative Amsterdam on 8 November. This meeting will focus on XSLT
issues.

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:END:

** Roll call
:PROPERTIES:
:CUSTOM_ID: roll-call
:END:

Regrets BTW, NW, JL, and CG. MSM to chair.

** Select a scribe
:PROPERTIES:
:CUSTOM_ID: h-D8BAA332-74D3-46FE-A439-68B7A50D8E88
:END:

** Accept the agenda
:PROPERTIES:
:CUSTOM_ID: accept-agenda
:END:

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:END:

Regrets for the next meeting?

** Approve minutes of previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:END:

Minutes of [[../../minutes/2022/11-01.html][the previous meeting]].

** Review of  open action items [2/6]
:PROPERTIES:
:CUSTOM_ID: open-actions
:END:

(Items marked [X] are believed to have been closed via email before
this agenda was posted.)

+ [ ] QT4CG-002-10: BTW to coordinate some ideas about improving diversity in the group
+ [ ] QT4CG-007-05: NW to make an issue for Martin’s proposed ammendment to map:build
+ [ ] QT4CG-009-01: NW to coordinate with MK on an agenda for next week.
+ [ ] QT4CG-009-02: NW to work with MK to make sure PR #197 is updated correctly
+ [ ] QT4CG-009-03: NW to investigate the relationship between PR #215 and =resolve-uri=.
+ [ ] QT4CG-009-04: NW to review RFC 3896 wrt relative URIs
+ [ ] QT4CG-009-05: NW to fix the return type for =parse-uri=; consider using a record type.
+ [ ] QT4CG-009-06: NW to add error tests for =parse-uri=.
+ [ ] QT4CG-009-06: NW to make the query segments an array of maps.

* Technical Agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:END:

** Extensions to conditional instructions
:PROPERTIES:
:CUSTOM_ID: h-57495EC0-C9D5-4F9E-BD59-B37E64D9B019
:END:

Approve extensions to conditional instructions described in [[https://qt4cg.org/specifications/xslt-40/Overview-diff.html#conditionals][chapter 8]]
of the current draft.

1. ~xsl:if~: ~@then~ and ~@else~ attributes
2. ~xsl:when~ and ~xsl:otherwise~: ~@select~ attribute
2. ~xsl:switch~ instruction

** Changes to modes
:PROPERTIES:
:CUSTOM_ID: h-249B03E7-22EA-4F3A-A6D6-A801BE8DB1C8
:END:

Review changes to modes in [[https://qt4cg.org/specifications/xslt-40/Overview-diff.html#modes][§6.7]]:

1. ~as~ attribute (detail is in [[https://qt4cg.org/specifications/xslt-40/Overview-diff.html#mode-result-type][§6.7.4]])
2. enclosed modes (detail is in [[https://qt4cg.org/specifications/xslt-40/Overview-diff.html#enclosed-modes][§6.7.5]])

** Review array construction
:PROPERTIES:
:CUSTOM_ID: h-08341AFB-91D3-49F4-976D-C5EA8A383216
:END:

See [[https://qt4cg.org/specifications/xslt-40/Overview-diff.html#array-construction][§22.1]].

MK says:

#+BEGIN_QUOTE
I don't think the text here is ready for approval; it needs open
discussion of the technical issues to make progress. The key question
is, what kind of value should xsl:array-member produce? This also
relates to how we iterate over arrays and maps.
#+END_QUOTE

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:END:

