:PROPERTIES:
:ID:       16D9F91C-8E95-4781-B646-72E5969BAE91
:END:
#+title: QT4 CG Meeting 026 Agenda 2023-03-14
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

* Agenda
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: agenda
:END:

This meeting will be hosted on Zoom at 16:00GMT (17:00CET, 12:00EDT, 09:00PDT).

ATTENTION: This meeting is scheduled at 16:00 local time in Europe and the UK.
The United States switched to Daylight Saving Time starting on Sunday,
12 March 2023. Until Europe and the UK switch to summer time (on 26
March 2023), this meeting will be one hour *later* in the United
States.

See the [[https://qt4cg.org/meeting/logistics.html][meeting logistics]] page for details.

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:END:

** Roll call
:PROPERTIES:
:CUSTOM_ID: roll-call
:END:

** Approve the agenda
:PROPERTIES:
:CUSTOM_ID: accept-agenda
:END:

** Approve minutes of previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:END:

Minutes of [[../../minutes/2023/03-07.html][the previous meeting]].

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:END:

This meeting is planned for
14 March,
the following meeting is scheduled for
21 March.

Any regrets for the following meeting?

** Review of open action items [6/15]
:PROPERTIES:
:CUSTOM_ID: open-actions
:END:

(Items marked [X] are believed to have been closed via email before
this agenda was posted.)

+ [ ] QT4CG-002-10: BTW to coordinate some ideas about improving diversity in the group
+ [ ] QT4CG-016-08: RD to clarify how namespace comparisons are performed.
+ [ ] QT4CG-023-01: NW to review the stylesheets for functions across XPath and XSLT
+ [X] QT4CG-023-05: NW to put record types on an agenda.
+ [ ] QT4CG-024-01: MK to add namespace-uri-for-prefix argument changes to the compatibility appendix
+ [ ] QT4CG-024-02: DN to develop an alternative proposal for deep-action.
+ [X] QT4CG-025-01: NW to close the issues we agreed to close in meeting 024
+ [ ] QT4CG-025-02: MK to make the context function properties simple values instead of functions
+ [ ] QT4CG-025-03: MK to revise and expand technical detail in PR #375
+ [ ] QT4CG-025-04: RD to remove the note in 15.5.15 of functions and operators.
+ [X] QT4CG-025-05: MK to correct the accidental deletion in 3.6.2 of XQuery
+ [X] QT4CG-025-06: NW to fix the “blue boxes” in the serialization specification
+ [X] QT4CG-025-07: MK to update the text about for/let changes to use use definitions and termrefs correctly.
+ [X] QT4CG-025-08: MK to add an error code for the case where =member= is used on something that isn’t an array
+ [ ] QT4CG-025-09: NW to add the parse-uri and build-uri tests to the test suite

* Technical Agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:END:

This agenda begins with record types, proposed for the agenda some
weeks ago, followed by a few more substantial PRs then a few small PRs.

** Record types
:PROPERTIES:
:CUSTOM_ID: h-29A87C61-D673-4C02-AF2C-DC56FD7B0F9F
:END:

In [[https://qt4cg.org/meeting/minutes/2023/02-21.html#h-5ACE0622-A613-4026-9074-C7492E84CC15][meeting 023]], we encountered the proposal for a new pattern syntax,
~(type(T), record(N, M, N))~ that allows matching of items by item type.
This needs CG discussion.

** PR #368: Issue 129 - Context item generalized to context value
:PROPERTIES:
:CUSTOM_ID: h-29972C1F-44ED-4967-A11B-87E12F9B9123
:END:

See PR [[https://qt4cg.org/dashboard/#pr-368][#368]].

** PR #360: Issue 314 array composition and decomposition
:PROPERTIES:
:CUSTOM_ID: h-6315DE9C-ACA9-43A8-8380-8F63EC6AF78F
:END:

See PR [[https://qt4cg.org/dashboard/#pr-360][#360]]

** PR #320: Issue 98 - add options parameter to fn:deep-equal
:PROPERTIES:
:CUSTOM_ID: h-9B6FD30F-50B9-4CE0-B89B-DBFB25C6F045
:END:

See PR [[https://qt4cg.org/dashboard/#pr-320][#320]].

** PR #387: Add compatibility notes for fn:namespace-uri-for-prefix 
:PROPERTIES:
:CUSTOM_ID: h-8A6DEAFA-1767-4AD5-863B-356CA5C3296B
:END:

See PR [[https://qt4cg.org/dashboard/#pr-387][#387]].

** PR #385: Actions QT4CG-025-07 / -08
:PROPERTIES:
:CUSTOM_ID: h-BF46187E-C2F8-482F-955F-BEA03C033446
:END:

See PR [[https://qt4cg.org/dashboard/#pr-385][#385]].

** PR #391: addressed typographical errors; …
:PROPERTIES:
:CUSTOM_ID: h-6040B099-6618-487B-9299-6C7E9BB92AB9
:END:

See PR [[https://qt4cg.org/dashboard/#pr-391][#391]].

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:END:


