:PROPERTIES:
:ID:       772A2C41-720A-4852-99CB-04EBD2EDA776
:END:
#+title: QT4 CG Meeting 027 Agenda 2023-03-21
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

* Agenda
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: agenda
:END:

This meeting will be hosted on Zoom at 16:00GMT (17:00CET, 12:00EDT, 09:00PDT).

ATTENTION: This meeting is scheduled at 16:00 local time in Europe and the UK.
The United States switched to Daylight Saving Time starting on Sunday,
12 March 2023. Until Europe and the UK switch to summer time (on 26
March 2023), this meeting will be one hour *later* in the United
States.

See the [[https://qt4cg.org/meeting/logistics.html][meeting logistics]] page for details.

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:END:

** Roll call
:PROPERTIES:
:CUSTOM_ID: roll-call
:END:

** Approve the agenda
:PROPERTIES:
:CUSTOM_ID: accept-agenda
:END:

** Approve minutes of previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:END:

Minutes of [[../../minutes/2023/03-14.html][the previous meeting]].

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:END:

This meeting is planned for
21 March,
the following meeting is scheduled for
28 March.

Any regrets for the following meeting?

** Review of open action items [1/9]
:PROPERTIES:
:CUSTOM_ID: open-actions
:END:

(Items marked [X] are believed to have been closed via email before
this agenda was posted.)

+ [ ] QT4CG-002-10: BTW to coordinate some ideas about improving diversity in the group
+ [ ] QT4CG-016-08: RD to clarify how namespace comparisons are performed.
+ [ ] QT4CG-023-01: NW to review the stylesheets for functions across XPath and XSLT
+ [ ] QT4CG-024-01: MK to add namespace-uri-for-prefix argument changes to the compatibility appendix
+ [X] QT4CG-024-02: DN to develop an alternative proposal for deep-action.
+ [ ] QT4CG-025-02: MK to make the context function properties simple values instead of functions
+ [ ] QT4CG-025-03: MK to revise and expand technical detail in PR #375
+ [ ] QT4CG-025-04: RD to remove the note in 15.5.15 of functions and operators.
+ [ ] QT4CG-026-01: MK to write a summary paper that outlines the decisions we need to make on “value sequences”

* Technical Agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:END:

** PR #391: addressed typographical errors; adjusted Unicode character discussion…
:PROPERTIES:
:CUSTOM_ID: pr-391
:END:

See PR [[https://qt4cg.org/dashboard/#pr-391][pull request #391]]

** PR #393: Clarify explanations of functions/function items
:PROPERTIES:
:CUSTOM_ID: pr-393
:END:

See PR [[https://qt4cg.org/dashboard/#pr-393][pull request #393]]

** PR #394: Minor correction to fn:parse-uri
:PROPERTIES:
:CUSTOM_ID: pr-394
:END:

See PR [[https://qt4cg.org/dashboard/#pr-394][pull request #394]]

** PR #395: Make the (non-)hierarchical nature of URIs explicit
:PROPERTIES:
:CUSTOM_ID: pr-395
:END:

See PR [[https://qt4cg.org/dashboard/#pr-395][pull request #395]]

** PR #396: Deep-equal, no failure when comparing functions
:PROPERTIES:
:CUSTOM_ID: pr-396
:END:

See PR [[https://qt4cg.org/dashboard/#pr-396][pull request #396]]

** PR #400: Issue 400: ranking of type patterns
:PROPERTIES:
:CUSTOM_ID: pr-400
:END:

See PR [[https://qt4cg.org/dashboard/#pr-400][pull request #400]]

** Issue #399: Using Multilevel Hierarchy and Abstraction…deep-equal
:PROPERTIES:
:CUSTOM_ID: iss-399
:END:

See [[https://qt4cg.org/dashboard/#pr-399][issue #399]]

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:END:


