:PROPERTIES:
:ID:       F8DF2884-0D56-4720-80B5-162F8B0BF0BA
:END:
#+title: QT4 CG Meeting 029 Agenda 2023-04-04
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

* Agenda
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: agenda
:END:

This meeting will be hosted on Zoom at 16:00BST (17:00CEST, 11:00EDT, 08:00PDT).

See the [[https://qt4cg.org/meeting/logistics.html][meeting logistics]] page for details.

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:END:

** Roll call
:PROPERTIES:
:CUSTOM_ID: roll-call
:END:

** Approve the agenda
:PROPERTIES:
:CUSTOM_ID: accept-agenda
:END:

** Approve minutes of previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:END:

Minutes of [[../../minutes/2023/03-28.html][the previous meeting]].

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:END:

This meeting is planned for
4 April,
the following meeting is scheduled for
11 April.

Any regrets for the following meeting?

** Review of open action items [1/9]
:PROPERTIES:
:CUSTOM_ID: open-actions
:END:

(Items marked [X] are believed to have been closed via email before
this agenda was posted.)

+ [ ] QT4CG-002-10: BTW to coordinate some ideas about improving diversity in the group
+ [ ] QT4CG-016-08: RD to clarify how namespace comparisons are performed.
+ [ ] QT4CG-023-01: NW to review the stylesheets for functions across XPath and XSLT
+ [ ] QT4CG-025-03: MK to revise and expand technical detail in PR #375
+ [ ] QT4CG-026-01: MK to write a summary paper that outlines the decisions we need to make on “value sequences”
+ [ ] QT4CG-027-01: MK to update the text for next-match wrt type() matching
+ [ ] QT4CG-028-01: MK to summarize the options available wrt deep equal and errors

* Technical Agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:END:

In response to feedback from last week, this agenda includes more
issues and fewer PRs. MSM and I reviewed the issues list and selected
a group of issues that (a) looked like they would benefit from
discussion and (b) were not marked Feature or Enhancement. (We
obviously need to discuss enhancements and features too, but focusing
on bugs and errors seemed like a good initial strategy.)

I propose an initial 15 minute time box on each issue. If, after 10
minutes, if we aren’t closing in on a resolution, let’s work out what
we need to do to improve our chances of being able to resolve it next
time. 

** PR #411: Remove the note from the parse-html unparsed-entity sections
:PROPERTIES:
:CUSTOM_ID: h-F1FFD1AB-0328-4748-8384-BA8AD7A2C576
:END:

See [[https://qt4cg.org/dashboard/#pr-411][issue #411]]

** Issue #399: Using Multilevel Hierarchy and Abstraction…deep-equal
:PROPERTIES:
:CUSTOM_ID: iss-399
:END:

See [[https://github.com/qt4cg/qtspecs/issues/399][issue #399]]

** Issue #280: Why is resolve-uri forbidden … a fragment identifier?
:PROPERTIES:
:CUSTOM_ID: iss-280
:END:

See [[https://github.com/qt4cg/qtspecs/issues/280][issue 280]].

** Issue #293: Error in fn:doc-available specification
:PROPERTIES:
:CUSTOM_ID: iss-293
:END:

See [[https://github.com/qt4cg/qtspecs/issues/293][issue 293]].

** Issue #315: fn:transform inconsistency: initial-mode
:PROPERTIES:
:CUSTOM_ID: iss-315
:END:

See [[https://github.com/qt4cg/qtspecs/issues/315][issue 315]].

** Issue #367: Focus for RHS of thin arrow expressions
:PROPERTIES:
:CUSTOM_ID: iss-367
:END:

See [[https://github.com/qt4cg/qtspecs/issues/367][issue 367]].

** Issue #397: Type names
:PROPERTIES:
:CUSTOM_ID: iss-397
:END:

See [[https://github.com/qt4cg/qtspecs/issues/397][issue 397]].

** Issue #334: Transient properties: a new approach to deep selection…
:PROPERTIES:
:CUSTOM_ID: iss-334
:END:

See [[https://github.com/qt4cg/qtspecs/issues/334][issue 334]].

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:END:


