:PROPERTIES:
:ID:       7F3369F5-3A0D-46C1-B47E-8F2BFE675089
:END:
#+title: QT4 CG Meeting 076 Minutes 2024-05-07
#+author: CMSMcQ 
#+filetags: :qt4cg:
#+options: html-style:nil h:6
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

* Administrivia
:PROPERTIES:
:CUSTOM_ID: h-5FD58640-0C4C-47AD-9DD2-CE42E3859295
:END:

Approved [[../2024/05-14.html][at meeting 077]] on 14 May 2024.

** Roll call
:PROPERTIES:
:CUSTOM_ID: h-F610AA71-DC40-4E3E-A05D-568CABACE015
:END:

Regrets from NW, JLY. MSM to chair. [7/12]

- [ ] Reece Dunn (RD). /Regrets./
- [ ] Sasha Firsov (SF)
- [X] Christian Grün (CG)
- [X] Joel Kalvesmaki (JK)
- [X] Michael Kay (MK)
- [ ] Juri Leino (JLO)
- [ ] John Lumley (JLY). /Regrets./
- [X] Dimitre Novatchev (DN)
- [X] Wendell Piez (WP)
- [X] Ed Porter (EP)
- [X] C. M. Sperberg-McQueen (MSM). /Scribe. Chair./
- [ ] Norm Tovey-Walsh (NW). /Regrets./


** Approve the agenda
:PROPERTIES:
:CUSTOM_ID: h-B1C3720D-A852-416F-8CA8-F796F8B4928E
:END:

Proposal:  Accept [[https://qt4cg.org/meeting/agenda/2024/05-07.html][the agenda]] as posted.

MK says that PR #1181 belongs in the general list, not XSLT-focused, as
it affects all specs.

CG: can we prioritize 1068?

Accepted as modified.

** Approve minutes of previous meeting
:PROPERTIES:
:CUSTOM_ID: h-AD4E2248-E237-42B4-987B-745B7073F0BD
:END:

MSM urged the group to look carefully at the status visualizations at
the beginning of each week's minutes.  The number of open bugs is
improving, but (a) the overall trend line is still ascending and (b)
the number of issues is still well into triple digits.

Proposal:  Accept [[https://qt4cg.org/meeting/minutes/2024/04-30.html][minutes of the previous meeting]].

Accepted.

** Next meeting
:PROPERTIES:
:CUSTOM_ID: h-6E415DD8-5C33-4E06-A5CA-DB9AC4955455
:END:

The next meeting is scheduled for
[[https://qt4cg.org/meeting/agenda/2024/05-14.html][14 May]]. The following
meeting is scheduled for 21 May.

MSM noted that he and NW have a conflicting meeting, but having just
harangued the group on the subject of improving the burn-down rate, he
felt incapable of proposing that we skip the meeting.  So: we *will*
meet on 14 May, and NW and MSM will have to sneak out of their other
meeting.


** Review of open action items [1/7]
:PROPERTIES:
:CUSTOM_ID: h-1C7F6C83-ADC6-4CE8-9C43-C68FC17DFCF3
:END:

(Items marked [X] are believed to have been closed via email before this agenda was posted.)

- [ ] QT4CG-063-06: MK to consider refactoring the declare item type syntax to something like declare record
- [ ] QT4CG-071-06: NW to clarify the cases that are distinguished by the leading empty string in path segments
- [ ] QT4CG-072-03: NW to clarify the round-tripping of URIs
- [ ] QT4CG-073-01: NW to proceed with the records/options proposal and make a PR.
- [ ] QT4CG-075-01: MK to drop the deterministic option and raise it as a separate issue.
- [ ] QT4CG-075-02: MK to define sequence-concatenation more formally with links where appropriate
- [X] QT4CG-075-03: CG to make changes to map:values analagous to MK’s changes to array:values

MK reports he's done half of 075-01.  

CG has made a PR satisfying 075-03.

** Review of open pull requests and issues
:PROPERTIES:
:CUSTOM_ID: h-B9D86C17-B569-479B-9148-AA10721BBA6C
:END:

*** XSLT focused
:PROPERTIES:
:CUSTOM_ID: h-2E27F717-E026-4E76-8867-3D13A65059E3
:END:

The following PRs appear to be candidates for a future XSLT-focused
meeting.

  - PR [[https://qt4cg.org/dashboard/#pr-1015][#1015]]: 1013 [XSLT] Clarify
effect of accumulator capture on non-element nodes
  - PR [[https://qt4cg.org/dashboard/#pr-921][#921]]: 920 Allow xsl:break and
xsl:next-iteration within branch of xsl:switch
  - PR [[https://qt4cg.org/dashboard/#pr-871][#871]]: Action qt4 cg 027 01 next match

These issues identify the XSLT-focused changes that have been made to
the specifications but which have not been established by the
community group as the status quo.

  - Issue [[https://github.com/qt4cg/qtspecs/issues/168][#168]]: XSLT Extension
Instructions invoking Named Templates

We removed PR [[https://qt4cg.org/dashboard/#pr-1181][#1181]] from this list and moved it to the next section.

*** Substantive PRs
:PROPERTIES:
:CUSTOM_ID: h-777CB2A2-C144-480C-859C-1A2E43163364
:END:

The following substantive PRs were open when this agenda was prepared.

  - PR [[https://qt4cg.org/dashboard/#pr-1186][#1186]]: 1170 Editorial: fn:index-where
  - PR [[https://qt4cg.org/dashboard/#pr-1185][#1185]]: 1179 array:values, map:values → contents
  - PR [[https://qt4cg.org/dashboard/#pr-1184][#1184]]: 1165-Use Unicode-style character references
  - PR [[https://qt4cg.org/dashboard/#pr-1182][#1182]]: 1171 Change predicate
callbacks to allow empty return value
  - PR [[https://qt4cg.org/dashboard/#pr-1148][#1148]]: 1143 Coercion rules:
handle choice types before atomization
  - PR [[https://qt4cg.org/dashboard/#pr-1117][#1117]]: 1116 Add options param to unparsed-text
  - PR [[https://qt4cg.org/dashboard/#pr-1108][#1108]]: 566-partial Describe a
less aggressive %-encoding for fn:build-uri
  - PR [[https://qt4cg.org/dashboard/#pr-1098][#1098]]: 566-partial Editorial improvements for parse-uri
  - PR [[https://qt4cg.org/dashboard/#pr-1068][#1068]]: 73 fn:graphemes
  - PR [[https://qt4cg.org/dashboard/#pr-1062][#1062]]: 150bis - revised proposal for fn:ranks
  - PR [[https://qt4cg.org/dashboard/#pr-1027][#1027]]: 150 fn:ranks

We added:

  - PR [[https://qt4cg.org/dashboard/#pr-1181][#1181]]: 296 Allow default-namespace=##any
    

* Technical Agenda
:PROPERTIES:
:CUSTOM_ID: h-92D0ACD0-9BC3-4389-9479-CBEBFC2419E2
:END:

** PR [[https://qt4cg.org/dashboard/#pr-1186][#1186]]: 1170 Editorial: fn:index-where
:PROPERTIES:
:CUSTOM_ID: h-C7830527-6C52-4E7B-AFCF-A826F4B1F550
:END:

See PR [[https://qt4cg.org/dashboard/#pr-1186][#1186]].

Accept and close.

** PR [[https://qt4cg.org/dashboard/#pr-1185][#1185]]: 1179 array:values, map:values → contents
:PROPERTIES:
:CUSTOM_ID: h-0B28CDC3-EB80-49BD-8171-A9E7BC2E019F
:END:

See PR [[https://qt4cg.org/dashboard/#pr-1185][#1185]].

MK: the problem is that 'contains' looks at keys, and 'contents' looks
at key-values.

MSM: 'value' is overloaded; that's part of theproblem, right?

CG maybe item?

DN: sequence concatenation in undefined order?  Yow!

These functions lose the structure!  This isn't a great way to get at
the parts of an array or map.

MK: Yes.  But so many arrays have singleton values that the
requirement to move from array to sequence is a very common one.

JK: what's the intended difference between array:content() and
array:flatten()?  CG: contents() is much simpler.

CG: the motivation for these is to allow functional equivalents for a
widely used wildcard syntax.

Various people: would 'flatten' be a better name?

CN: or flattened-value()?

CN:  loss of information is the issue.  array:squashed(),  maps:squashed().

Further consideration needed.  Take it offline.



** PR [[https://qt4cg.org/dashboard/#pr-1184][#1184]]: 1165-Use Unicode-style character references
:PROPERTIES:
:CUSTOM_ID: h-D8882D53-D962-4A76-8AF6-68CCA1B84C9A
:END:

See PR [[https://qt4cg.org/dashboard/#pr-1184][#1184]].

MK: purely editorial.

Accepted.

** PR [[https://qt4cg.org/dashboard/#pr-1182][#1182]]: 1171 Change predicate
:PROPERTIES:
:CUSTOM_ID: h-55CEF04C-9E1E-48A3-A445-20A06CD23939
:END:
callbacks to allow empty return value

See PR [[https://qt4cg.org/dashboard/#pr-1182][#1182]].

Accepted.


** PR [[https://qt4cg.org/dashboard/#pr-1148][#1148]]: 1143 Coercion rules:
:PROPERTIES:
:CUSTOM_ID: h-706A7B88-ABA8-4A39-A41C-D3FAF396F7E0
:END:
handle choice types before atomization

See PR [[https://qt4cg.org/dashboard/#pr-1148][#1148]]

DN asks for more examples.  Text nodes?

ACTION:  MK to draft an editorial proposal to add more examples.

* Any other business
:PROPERTIES:
:CUSTOM_ID: h-BE122C76-CD86-48A2-9360-6E61E3C3BC85
:END:

None.
