:PROPERTIES:
:ID:       6B4DAE75-FA6A-4FA7-B637-02F147E7D5BD
:END:
#+title: QT4 CG Meeting 152 Minutes 2026-02-10
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

[[../][Meeting index]] / [[https://qt4cg.org][QT4CG.org]] / [[https://qt4cg.org/dashboard][Dashboard]] / [[https://github.com/qt4cg/qtspecs/issues][GH Issues]] / [[https://github.com/qt4cg/qtspecs/pulls][GH Pull Requests]]

#+TOC: headlines 6

* Minutes
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: minutes
:END:

Approved [[../2026/02-17.html][at meeting 153]] on 17 February 2026.

* Summary of new and continuing actions [0/5]
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: new-actions
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-143-03: JK to look for C14N test suites.
+ [ ] QT4CG-144-01: MK to consider if any now lost value comparisons should be added as examples.
+ [ ] QT4CG-149-01: CG to draft a new PR with the common rule note.
+ [ ] QT4CG-150-01: NW to ask Jirka for a room at XML Prague for Tuesday/Wednesday
+ [ ] QT4CG-150-02: *Everyone* review the “nice to have” tags and object where they wish
+ [ ] QT4CG-150-03: NW to setup an agenda item to review open issues
+ [ ] QT4CG-150-04: NW to see about a status update on PR #2345; possibly schedule discussion
+ [ ] QT4CG-151-01: MK to fix the typo in the build-dateTime function.
+ [ ] QT4CG-151-03: NW to investigate why records are formatted incorrectly in XSLT
+ [ ] QT4CG-152-01: MK to add a note about the new and old syntax for names in PR #2446

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:END:

** Roll call [9/10]
:PROPERTIES:
:CUSTOM_ID: roll-call
:END:

Regrets: WP.

+ [X] David J Birnbaum (DB) [x:06-]
+ [X] Reece Dunn (RD)
+ [X] Christian Grün (CG)
+ [X] Joel Kalvesmaki (JK) [x:05-]
+ [X] Michael Kay (MK)
+ [X] Juri Leino (JLO)
+ [X] John Lumley (JWL)
+ [X] Alan Painter (AP
+ [ ] Wendell Piez (WP)
+ [X] Norm Tovey-Walsh (NW) /Scribe/. /Chair/.

** Accept the agenda
:PROPERTIES:
:CUSTOM_ID: agenda
:END:

Proposal: Accept [[../../agenda/2026/02-10.html][the agenda]].

Accepted.

** Approve minutes of the previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:END:

Proposal: Accept [[../../minutes/2026/02-03.html][the minutes of the previous meeting]]. 

Accepted.

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:END:

The next meeting is planned for 17 February 2026.

DB gives regrets for 17 February.

** Review of open action items [1/11]
:PROPERTIES:
:CUSTOM_ID: open-actions
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-143-03: JK to look for C14N test suites.
+ [ ] QT4CG-144-01: MK to consider if any now lost value comparisons should be added as examples.
+ [ ] QT4CG-149-01: CG to draft a new PR with the common rule note.
+ [ ] QT4CG-150-01: NW to ask Jirka for a room at XML Prague for Tuesday/Wednesday
+ [ ] QT4CG-150-02: *Everyone* review the “nice to have” tags and object where they wish
+ [ ] QT4CG-150-03: NW to setup an agenda item to review open issues
+ [ ] QT4CG-150-04: NW to see about a status update on PR #2345; possibly schedule discussion
+ [ ] QT4CG-151-01: MK to fix the typo in the build-dateTime function.
+ [X] QT4CG-151-02: NW to generate compiled schema, merge #2404.
+ [ ] QT4CG-151-03: NW to investigate why records are formatted incorrectly in XSLT

** Review of open pull requests and issues
:PROPERTIES:
:CUSTOM_ID: open-pull-requests
:END:

This section summarizes all of the issues and pull requests that need to be
resolved before we can finish. See [[#technical-agenda][Technical Agenda]] below for the focus of this
meeting.

*** Blocked
:PROPERTIES:
:CUSTOM_ID: blocked
:END:

The following PRs are open but have merge conflicts or comments which
suggest they aren’t ready for action.

+ PR [[https://qt4cg.org/dashboard/#pr-2313][#2313]]: 2298 XQFO rules: definition of default values
+ PR [[https://qt4cg.org/dashboard/#pr-2266][#2266]]: 540 system-property equivalent for XQuery
+ PR [[https://qt4cg.org/dashboard/#pr-2160][#2160]]: 2073 data model changes for JNodes and Sequences
+ PR [[https://qt4cg.org/dashboard/#pr-2071][#2071]]: 77c deep update
+ PR [[https://qt4cg.org/dashboard/#pr-2019][#2019]]: 1776: XSLT template rules for maps and array

*** Merge without discussion
:PROPERTIES:
:CUSTOM_ID: merge-without-discussion
:END:

The following PRs are editorial, small, or otherwise appeared to be
uncontroversial when the agenda was prepared. The chairs propose that
these can be merged without discussion. If you think discussion is
necessary, please say so.

+ PR [[https://qt4cg.org/dashboard/#pr-2440][#2440]]: 2432 Clarify effect of coercion on constructor functions
+ PR [[https://qt4cg.org/dashboard/#pr-2439][#2439]]: Fix prefix on bin:int-octets example function

Proposal: merge without discussion.

Accepted.

*** Close without action
:PROPERTIES:
:CUSTOM_ID: close-without-action
:END:

It has been proposed that the following issues be closed without action.
If you think discussion is necessary, please say so.

+ Issue [[https://github.com/qt4cg/qtspecs/issues/2436][#2436]]: `jnode` type: arguments (spec vs. tests)

Proposal: close without further action.

Accepted.

* Technical agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:END:

** PR #2452: 2450 Add jnode((), *) to match root JNodes
:PROPERTIES:
:CUSTOM_ID: pr-2452
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2452][#2452]].

+ MK: This arose in the context of match patterns in XSLT. What’s the equivalent
  of “/” for a JNode tree?
  + … There wasn’t a convenient way of doing it; I proposed a change to the type
    syntax to cover this case and keep them aligned.
+ MK: We get a ~JRootSelector~ in ~JNodeType~. I considered “/”, but CG proposed “()”.
  + … I took the opportunity to clarify the text a bit.

MK reviews the clarified rules.

Some discussion of the differences between “*” for XNode and JNode trees.

+ MK: Added some more examples.
+ MK: It migrates into XSLT patterns as well.

Proposal: accept this PR.

Accepted.

** PR #2451: 2444 Make match="*" and match="N" match element nodes only
:PROPERTIES:
:CUSTOM_ID: pr-2451
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2451][#2451]].

+ MK: The current rules for axis steps are that an axis step of “*” will match
  an element if you’re starting at an XNode and a JNode with any selector
  starting at a JNode.
  + … I found it was hard to implement the semantics for that, especially with
    streaming. You can’t do precise type checking. And it’s a bit of a usability
    problem.
  + … If you have a lot of match="N" predicates and you add support for JNodes
    somewhere, that changes all the semantics. That’s a probably going to
    introduce bugs.
+ MK: Match="*" and match="N" have been clarified to say they don’t match
  JNodes. To match JNodes you have to be explicit.
  + … XSLT 3.x tried to identify the leading steps but it didn’t work. I’ve fixed that.
  + … We add new magic that if the node test is an EQName or Wildcard, we wrap
    it in an element test. So ~match="N"~ is ~match="element(N)"~
  + … A few examples are updated.
+ MK: It was tricky to get right, but it’s a fairly small change.

MK observes that this doesn’t effect path expressions; it only applies to XSLT
match patterns.

Proposal: accept this PR.

Accepted.

** PR #2449: 2445 Add rules for xsi namespace elements in element-to-map
:PROPERTIES:
:CUSTOM_ID: pr-2449
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2449][#2449]].

+ MK: We had examples that we clearly ignored ~xsi:~ attributes, but I couldn’t
  find anything in the spec to justify that.
  + … There is some special handling of ~xsi:nil~.
  + … This PR makes the text reflect the examples.
+ MK: Adds a new section, 14.5.3 Attributes in the xsi namespace.

MK reviews the new rules in the section.

+ JLO: What example does this apply to?
+ MK: The attributes that you get in the xsi namespace are all to control schema
  validation.
  + … It’s unlikely you’d want those in your JSON; they don’t mean anything in that world.
  + … ~xsi:nil~ says that the contents of this element are nil; like null in SQL.
  + … The schema location and type attributes tell you where to find the schema
    and how subtyping works.
  + … If you’re in a vocabulary that uses ~xsi:type~, you’re probably best-off
    doing some pre-transformation to put that information in a more sensible
    form for the JSON.

Proposal: accept this PR.

Accepted.

** PR #2446: 2427 Add computed node constructors to XPath
:PROPERTIES:
:CUSTOM_ID: pr-2446
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2446][#2446]].

+ MK: I’ve proposed that we add functions to create nodes to XPath several
  times. I’ve had pushback on the grounds that if you’re in XQuery, there are
  now two ways to do it.
  + … I prefer to use functions, but in the interest of not having that
    duplication, this adds a subset of XQuery capability to XPath.
  + … It doesn’t add direct constructors, that makes it simpler.
  + … It doesn’t introduce some of the options that XQuery gives you, such as
    whether or not to inherit namespaces. This proposal takes the default
    options.
+ MK: The main difficulty was actually integrating the text into the spec!
+ MK: The constructed element namespace rule moves into XPath.
  + … A ~NodeConstructor~ is one of the ~PrimaryExpr~; it’s only allowed to be a
    ~ComputedConstructor~.
+ MK: New section, 4.13 Node Constructors
  + … Seven kinds of nodes.
  + … I’ve pulled out a section a bout constructing complex content that was
    previously five levels deep.
  + … A more amibitious scheme would be to have a single set of rules for XPath,
    XQuery, and XSLT. I haven’t tried to do that (yet).
+ MK: It’s the rules we’re familiar with…flatten arrays, merge items, etc.
  + … That’s the same as the XQuery rules with default options.
+ MK: Next is the specific grammar; it’s subsetted so that the name part must
  either be a QName literal or a computed expression. We haven’t retained the
  option of a bare name without the hash. That gave us syntax ambiguity problems in XQuery.
+ MK: There’s a lot of text, but most of it is old text rearranged.

MK would like a more comprehensive review, so perhaps not merge it today.

+ MK: In XQuery, there are a few editorial changes.
  + … The examples have been changed to use the new #name syntax.
+ MK: So XQuery doesn’t change technically, just some editorial changes.
 
+ JWL: The use of QName literal in XQuery doesn’t mean it’s deprecated does it?
  + … It’s a preference, I wonder if that needs to be emphasized. We don’t want
    users to think they have to change all their code!
+ MK: I can certainly add a note.

ACTION QT4CG-152-01: MK to add a note about the new and old syntax for names in PR #2446

Proposal: will put this in the “merge without discussion list” next week

** PR #2441: 2434 Fix inconsistencies with GNode tests in axis steps
:PROPERTIES:
:CUSTOM_ID: pr-2441
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2441][#2441]].

+ MK: Allows child::gnode(), removed self::array(*), allow functions that accept
  to the context item to accept GNodes.
+ JWL: Does that mean that the ~self:~ axis test can be used on a JNode?
+ MK: Yes.

Proposal: accept this PR.

Accepted.

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:END:

None heard.
