:PROPERTIES:
:ID:       BD1CEEE9-B4C6-420B-B95B-228B382AA83A
:END:
#+title: QT4 CG Meeting 156 Minutes 2026-03-17
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

[[../][Meeting index]] / [[https://qt4cg.org][QT4CG.org]] / [[https://qt4cg.org/dashboard][Dashboard]] / [[https://github.com/qt4cg/qtspecs/issues][GH Issues]] / [[https://github.com/qt4cg/qtspecs/pulls][GH Pull Requests]]

#+TOC: headlines 6

* Summary of new and continuing actions [0/8]
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: new-actions
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-144-01: MK to consider if any now lost value comparisons should be added as examples.
+ [ ] QT4CG-150-01: NW to ask Jirka for a room at XML Prague for Tuesday/Wednesday
+ [ ] QT4CG-150-04: NW to see about a status update on PR #2345; possibly schedule discussion
+ [ ] QT4CG-156-01: MK: add reference to data model in F&O 9.2
+ [ ] QT4CG-156-02: MK: think though implications on strings arising from duplication in specs.
+ [ ] QT4CG-156-03: MK to revise PR #2516 in light of the comments. 
+ [ ] QT4CG-156-04: CG: Related to #2313, make some minor changes to the explanatory note.

* Draft Minutes
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: minutes
:END:

Approved [[../2026/03-24.html][at meeting 157]] on 24 March 2026.

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:END:

** Roll call [8/10]
:PROPERTIES:
:CUSTOM_ID: roll-call
:END:

Regrets: DB, NW

+ [ ] David J Birnbaum (DB)
+ [X] Reece Dunn (RD)
+ [X] Christian Grün (CG)
+ [X] Joel Kalvesmaki (JK) /Chair/.
+ [X] Michael Kay (MK)
+ [X] Juri Leino (JLO)
+ [X] John Lumley (JWL) /Scribe/
+ [X] Alan Painter (AP
+ [X] Wendell Piez (WP)
+ [ ] Norm Tovey-Walsh (NW)

NW thanks JK and JWL. Assume any errors introduced in the minutes are NW’s
fault.

** Accept the agenda
:PROPERTIES:
:CUSTOM_ID: agenda
:END:

Proposal: Accept [[../../agenda/2026/03-17.html][the agenda]].

Accepted.

** Approve minutes of the previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:END:

Proposal: Accept [[../../minutes/2026/03-10.html][the minutes of the previous meeting]].

Accepted.

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:END:

The next meeting is planned for 24 March 2026.

Note: Daylight Saving Time begins in North America on Sunday, 8 March. It does
not begin in the UK and Europe until Sunday, 29 March. The QT4CG
meets on UK and European civil time. The meeting of 24 March will
be *one hour later* in North America.

** Review of open action items [9/13]
:PROPERTIES:
:CUSTOM_ID: open-actions
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [X] QT4CG-143-03: JK to look for C14N test suites.
+ [ ] QT4CG-144-01: MK to consider if any now lost value comparisons should be added as examples.
+ [ ] QT4CG-150-01: NW to ask Jirka for a room at XML Prague for Tuesday/Wednesday
+ [ ] QT4CG-150-04: NW to see about a status update on PR #2345; possibly schedule discussion
+ [X] QT4CG-151-01: MK to fix the typo in the build-dateTime function.
+ [X] QT4CG-152-01: MK to add a note about the new and old syntax for names in PR #2446
+ [X] QT4CG-153-01: MK to investigate the indentation problem.
+ [X] QT4CG-153-02: MK to turn my suggestions on #1949 into a PR.
  + Close with no action; #1949 remains open
+ [X] QT4CG-154-01: MK to review why anyAtomicType didn’t, in fact, become a square box!
+ [X] QT4CG-154-02: MK to add a note about “tunneling” package parameters.
+ [X] QT4CG-155-01: MK to add an example of function coercion that uses ~?~.
+ [X] QT4CG-155-02: MK to clarify that the seconds value can be 59.9, etc. (exlusive vs. inclusive)

** Review of open pull requests and issues
:PROPERTIES:
:CUSTOM_ID: open-pull-requests
:END:

This section summarizes all of the issues and pull requests that need to be
resolved before we can finish. See [[#technical-agenda][Technical Agenda]] below for the focus of this
meeting.

*** Blocked
:PROPERTIES:
:CUSTOM_ID: blocked
:END:

The following PRs are open but have merge conflicts or comments which
suggest they aren’t ready for action.

+ PR [[https://qt4cg.org/dashboard/#pr-2345][#2345]]: 2299 Expand pipeline to allow arrow expression in path expression
  + MK: This isn’t really blocked; probably only semantic; MK
    to review the tags.
+ PR [[https://qt4cg.org/dashboard/#pr-2266][#2266]]: 540 system-property equivalent for XQuery
  + JK: This isn’t really blocked; probably only semantic; JK
    to review the tags.
+ PR [[https://qt4cg.org/dashboard/#pr-2160][#2160]]: 2073 data model changes for JNodes and Sequences
+ PR [[https://qt4cg.org/dashboard/#pr-2071][#2071]]: 77c deep update
+ PR [[https://qt4cg.org/dashboard/#pr-2019][#2019]]: 1776: XSLT template rules for maps and array

*** Merge without discussion
:PROPERTIES:
:CUSTOM_ID: merge-without-discussion
:END:

The following PRs are editorial, small, or otherwise appeared to be
uncontroversial when the agenda was prepared. The chairs propose that
these can be merged without discussion. If you think discussion is
necessary, please say so.

+ PR [[https://qt4cg.org/dashboard/#pr-2514][#2514]]: 2403 Use narrative results for examples in file module
  + JK has comments; MK to follow-up.
+ PR [[https://qt4cg.org/dashboard/#pr-2513][#2513]]: QT4CG-152-01 Add note explaining computed node constructor syntax
  + Accepted.
+ PR [[https://qt4cg.org/dashboard/#pr-2511][#2511]]: 2497 JNodes diagrams: selector → jkey, content → jvalue
  + Accepted.

*** Substantive PRs
:PROPERTIES:
:CUSTOM_ID: substantive
:END:

The following substantive PRs were open when this agenda was prepared.

+ PR [[https://qt4cg.org/dashboard/#pr-2522][#2522]]: 2520 Atomic Data Types based on XSD 1.1
+ PR [[https://qt4cg.org/dashboard/#pr-2519][#2519]]: 2000 Define named record types for the conversion plan
+ PR [[https://qt4cg.org/dashboard/#pr-2516][#2516]]: 2433 JTree function: Discuss JNode identity more fully
+ PR [[https://qt4cg.org/dashboard/#pr-2515][#2515]]: 2475 Unification of type syntax
+ PR [[https://qt4cg.org/dashboard/#pr-2504][#2504]]: alternative PR#2247: Attempt at a minimalist alternative for generators.
+ PR [[https://qt4cg.org/dashboard/#pr-2470][#2470]]: 1310 Functions fn:regex and ?matching-substrings
+ PR [[https://qt4cg.org/dashboard/#pr-2350][#2350]]: 708 An alternative proposal for generators
+ PR [[https://qt4cg.org/dashboard/#pr-2313][#2313]]: 2298 XQFO rules: definition of default values
+ PR [[https://qt4cg.org/dashboard/#pr-2247][#2247]]: 716 Deferred Evaluation in XPath - the f:generator record
+ PR [[https://qt4cg.org/dashboard/#pr-2019][#2019]]: 1776: XSLT template rules for maps and array

* Technical agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:END:

** PR #2522: 2520 Atomic Data Types based on XSD 1.1
:PROPERTIES:
:CUSTOM_ID: pr-2522
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2522][#2522]].

+ MK: Arose from comments from Sheila Thomson about XSD1.0 and 1.1 differences
  for the value spaces in dateTime, and let systems that have schema processing
  to relax these dependencies.

The PR restricts the ability to relax these limits on XSD1.1 default in various
version situations (see the diffs for detail) Also includes cases where coercion
may be carried out in the string representation space. Some changes in F&O

ACTION QT4CG-156-01: MK: add reference to data model in F&O 9.2

+ RD: i) There is a potential duplication in the XSLT spec with the data model
  spec. (Slightly different examples). Also some confusion about permitted
  character definitions between XSD 1.1 and 1.0 and extension of other permitted
  characters (that being '0'). MK: they should all refer to the data model, but
  there are some issues.

ACTION QT4CG-156-02: MK: think though implications on strings arising from duplication in specs.

Proposal: Accept this PR.

Accepted.

** PR #2519: 2000 Define named record types for the conversion plan
:PROPERTIES:
:CUSTOM_ID: pr-2519
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2519][#2519]].

+ MK: CG asked for a consistent record type of the plan data structure for the
  element-to-map() and corresponding plan generation functions. The proposal has
  a record type for the element plan and a separate record type for attributes.

An editorial change adding the predefined record types.

Proposal: Accept this PR.

Accepted.

** PR #2516: 2433 JTree function: Discuss JNode identity more fully
:PROPERTIES:
:CUSTOM_ID: pr-2516
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2516][#2516]].

+ MK: We didn't discuss JNode identity thoroughly enough - this addresses that,
  mainly as extended notes on the jtree() function. Possibly most effect on the
  elimination of duplicate JNodes within a path.
+ JLO: Is there some contradiction within these notes?
+ MK: These equalities only occur in the same JNode tree, and the requirement is
  to support optimisation such as inlining results.
+ RD: Unrolling a for loop over such a map might be such an example.
+ MK: e.g. multiple serialisations across a program with the same options could
  involve optimisation of build a common single map.
+ JLO: Not convinced - somewhat murky. 
+ MK: Don't want to repeat the problems node identity has raised in such
  optimisation situations. If you select the same parts by different paths then
  you will get the same JNodes. If you have an array with 17 identical maps,
  then they can't be considered the same, provided they have been generated in
  through the same JTree
+ AP: Perhaps we should not rely on this - they are only guaranteed different if
  their contents differ.
+ CG: We might make it easier if we omit all implementation details. Who are we
  trying to communicate with in the spec?
+ WP: We have ~deep-equal()~ defined - what in addition are we trying to get.
+ MK: The main use is the elimination of duplicates. 
+ JLO: Have a clearer image now - might be easier to move the thrid paragraph to
  the top of section 16.1.1 - the jtree() function.

ACTION QT4CG-156-03: MK to revise PR #2516 in light of the comments. 

** PR #2515: 2475 Unification of type syntax
:PROPERTIES:
:CUSTOM_ID: pr-2515
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2515][#2515]].

+ MK: Didn't pick up all the suggestions from the issue. ElementTest and
  AttributeTest cahnged to type terms - purely terminology alterations.
  jnode(*,*) now unified to the element() and attribute()

Proposal: Accept the PR.

Accepted.

** PR #2504: alternative PR#2247: Attempt at a minimalist alternative for generators.
:PROPERTIES:
:CUSTOM_ID: pr-2504
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2504][#2504]].

Proposal: Close without action.

Accepted.

** PR #2470: 1310 Functions fn:regex and ?matching-substrings
:PROPERTIES:
:CUSTOM_ID: pr-2470
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2470][#2470]].

Not ready for discussion.

** PR #2313: 2298 XQFO rules: definition of default values
:PROPERTIES:
:CUSTOM_ID: pr-2313
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2313][#2313]].

+ CG: now use ~(:DEFAULT-ON-EMPTY:)~ rather than ~(:empty:)~ in the signatures,
  before the default value.

ACTION QT4CG-156-04: CG: Related to #2313, make some minor changes to the explanatory note.

Proposal: Accept this PR.

Accepted.

** PR #2019: 1776: XSLT template rules for maps and array
:PROPERTIES:
:CUSTOM_ID: pr-2019
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2019][#2019]].

Not ready for discussion.

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:END:

+ JK: Norm circulated a note on persistent diffs
  https://qt4cg.org/persistent-diffs/

Some discussion

+ MK: Had a little confusion on what to click
+ RD: Look at light/dark contrasts.

ACTION: ALL to look at this!

