:PROPERTIES:
:ID:       B551D819-0ECE-49FC-BCF1-8C33A779A313
:END:
#+title: QT4 CG Meeting 158 Minutes 2026-03-31
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

[[../][Meeting index]] / [[https://qt4cg.org][QT4CG.org]] / [[https://qt4cg.org/dashboard][Dashboard]] / [[https://github.com/qt4cg/qtspecs/issues][GH Issues]] / [[https://github.com/qt4cg/qtspecs/pulls][GH Pull Requests]]

#+TOC: headlines 6

* Summary of new and continuing actions [0/8]
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: new-actions
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-144-01: MK to consider if any now lost value comparisons should be added as examples.
+ [ ] QT4CG-150-01: NW to ask Jirka for a room at XML Prague for Tuesday/Wednesday
+ [ ] QT4CG-150-04: NW to see about a status update on PR #2345; possibly schedule discussion
+ [ ] QT4CG-156-01: MK: add reference to data model in F&O 9.2
+ [ ] QT4CG-156-03: MK to revise PR #2516 in light of the comments. 
+ [ ] QT4CG-157-01: CG to consider the issue of such empty directories
+ [ ] QT4CG-157-02: CG to propose an editorial change to use the fos:notes construct for the Notes. Also relevant to #2546
+ [ ] QT4CG-158-01: MK to revisit the Conformance section to revise in light of #2556 error changes
+ [ ] QT4CG-158-02: MK to add ~system-properties()~ keys for file and binary support

* Minutes
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: minutes
:END:

Approved [[../2026/04-07.html][at meeting 159]] on 7 April 2026.

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:END:

** Roll call [8/10]
:PROPERTIES:
:CUSTOM_ID: roll-call
:END:

Regrets: DB, NW

+ [ ] David J Birnbaum (DB)
+ [X] Reece Dunn (RD)
+ [X] Christian Grün (CG)
+ [X] Joel Kalvesmaki (JK) /Chair/.
+ [X] Michael Kay (MK)
+ [X] Juri Leino (JLO)
+ [X] John Lumley (JWL) /Scribe/
+ [X] Alan Painter (AP
+ [X] Wendell Piez (WP)
+ [ ] Norm Tovey-Walsh (NW)

NW thanks JK and JWL. Assume any errors introduced in the minutes are NW’s
fault.

** Accept the agenda
:PROPERTIES:
:CUSTOM_ID: agenda
:END:

Proposal: Accept [[../../agenda/2026/03-31.html][the agenda]].

Accepted with PR #2551 removed; issue 2.7 is not ready.

** Approve minutes of the previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:END:

Proposal: Accept [[../../minutes/2026/03-24.html][the minutes of the previous meeting]].

Accepted.

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:END:

The next meeting is planned for 7 April 2026.

JWL gives regrets for 7, 14, and 21 April.

** Review of open action items [0/8]
:PROPERTIES:
:CUSTOM_ID: open-actions
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-144-01: MK to consider if any now lost value comparisons should be added as examples.
+ [ ] QT4CG-150-01: NW to ask Jirka for a room at XML Prague for Tuesday/Wednesday
+ [ ] QT4CG-150-04: NW to see about a status update on PR #2345; possibly schedule discussion
+ [ ] QT4CG-156-01: MK: add reference to data model in F&O 9.2
+ [ ] QT4CG-156-03: MK to revise PR #2516 in light of the comments. 
+ [ ] QT4CG-157-01: CG to consider the issue of such empty directories
+ [ ] QT4CG-157-02: CG to propose an editorial change to use the fos:notes construct for the Notes. Also relevant to #2546

** Review of open pull requests and issues
:PROPERTIES:
:CUSTOM_ID: open-pull-requests
:END:

This section summarizes all of the issues and pull requests that need to be
resolved before we can finish. See [[#technical-agenda][Technical Agenda]] below for the focus of this
meeting.

*** Merge without discussion
:PROPERTIES:
:CUSTOM_ID: merge-without-discussion
:END:

The following PRs are editorial, small, or otherwise appeared to be
uncontroversial when the agenda was prepared. The chairs propose that
these can be merged without discussion. If you think discussion is
necessary, please say so.

+ PR [[https://qt4cg.org/dashboard/#pr-2563][#2563]]: 2562 Empty fields in parts-of-dateTime result now absent
+ PR [[https://qt4cg.org/dashboard/#pr-2560][#2560]]: 2321 Make fn:trace and fn:message nondeterministic
+ PR [[https://qt4cg.org/dashboard/#pr-2555][#2555]]: 2215 Add "see also" links between functions
+ PR [[https://qt4cg.org/dashboard/#pr-2545][#2545]]: 2544 Drop xsl:record-type/@extensible

Proposal: merge without discussion. 

Accepted.

+ PR [[https://qt4cg.org/dashboard/#pr-2551][#2551]]: 2550 Shadow attributes in RelaxNG schema
  + Moved to the technical agenda

*** Close without action
:PROPERTIES:
:CUSTOM_ID: close-without-action
:END:

It has been proposed that the following issues be closed without action.
If you think discussion is necessary, please say so.

+ Issue [[https://github.com/qt4cg/qtspecs/issues/2526][#2526]]: Facets
+ Issue [[https://github.com/qt4cg/qtspecs/issues/2325][#2325]]: Specify evaluation more tight and more formal to disallow unsane cases
+ Issue [[https://github.com/qt4cg/qtspecs/issues/2252][#2252]]: Dynamic XPath Evaluation the functional way

Proposal: close without further action.

Accepted.

*** Substantive PRs
:PROPERTIES:
:CUSTOM_ID: substantive
:END:

The following substantive PRs were open when this agenda was prepared.

+ PR [[https://qt4cg.org/dashboard/#pr-2559][#2559]]: 2549 Functional purity
+ PR [[https://qt4cg.org/dashboard/#pr-2558][#2558]]: 2556 errors for invisible-xml() and doc()
+ PR [[https://qt4cg.org/dashboard/#pr-2552][#2552]]: 540bis Add system-properties() function
+ PR [[https://qt4cg.org/dashboard/#pr-2533][#2533]]: 2528 Update RFC reference (7159 -> 8259) for JSON 
+ PR [[https://qt4cg.org/dashboard/#pr-2531][#2531]]: QT4CG-154-02 Revise rules for setting stylesheet parameters
+ PR [[https://qt4cg.org/dashboard/#pr-2516][#2516]]: 2433 JTree function: Discuss JNode identity more fully
+ PR [[https://qt4cg.org/dashboard/#pr-2019][#2019]]: 1776: XSLT template rules for maps and array

* Technical agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:END:

** PR #2559: 2549 Functional purity
:PROPERTIES:
:CUSTOM_ID: pr-2559
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2559][#2559]].

+ MK: arises from incorporating the File module. This needs a bit more detail
  and recommendations of the problem of possible side-effects on functional
  'purity'. A short essay to document current understanding.
  + … Explains what are the benefits of a functional language and the issues
    that might make this difficult. Eg. errors and node construction
    withidentity. Advice to users to mitigate or reduce the problems.
  + … Then some discussion of much more serious side-effecting functions.
  + … No attempt to tackle conformance rules.
  + .. No attempt to enumerate all the cases of side-effect caution.
+ JLO: Looks a good addition, giving guidance to both implementors and users.
  Would like to have some indication of side-effct risk on functions in the
  spec. 1.c - covers side-effects *other* than errors (comfirmed by MK)
+ AP: Could there be a 'lint-type' utility to identify problem ares for these side effects.
+ MK: Next stage could be to add something to the language to add this sort of check formnally.
+ CG: XQUery Update in their implementation has a non-deterministic property
  available, though it hasn't really been used. Would take a long time to do it
  all formally.

Proposal: accept this PR.

Accepted.

** PR #2558: 2556 errors for invisible-xml() and doc()
:PROPERTIES:
:CUSTOM_ID: pr-2558
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2558][#2558]].

+ MK: Started with ~invisible-xml()~ and it expanded to ~parse-xml()~ and thence ~doc()~
  + … Added specific errors for some of the violations, e.g. validation failure, unsupported options keywords
     (See the PR for the specific errors added)
  + … Arranged that ~parse-xml()~ and ~doc()~ use same wording in the
    descriptions ~invisible-xml()~ moves the error descriptions into an error
    conditions section. (Means lack of an invisible XML processor can raise an
    error rather than conformance failure, c.f the same with ~fn:transform()~)
+ JLO: Could we have more detailed error codes on ~parse-xml()~
+ MK:  Difficult with plug-in implementations.

ACTION QT4CG-158-01: MK to revisit the Conformance section to revise in light of #2556 error changes

Proposal: accept this PR.

Accepted.

** PR #2552: 540bis Add system-properties() function
:PROPERTIES:
:CUSTOM_ID: pr-2552
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2552][#2552]].

+ MK: Original idea was to add the XSLT system-property() function into XPAth,
  but those properties names are in the XSLT namespace. Solution to produce a
  new function, ~system-properties()~, which will use (add) no-namespace QNames,
  and is effectively a subset of the XSLT version. Can be a full replacement for
  ~system-property()~
+ JK: Will XSL properties be available in non-XSLT situations.
+ MK: No.
+ JK: What about adding supports-file, supports-binary.

ACTION QT4CG-158-02: MK to add ~system-properties()~ keys for file and binary support

+ JLO: Records can't be extended. Does this cause problems?
+ MK: No (some discussion)
+ CG: Would it be easier for users if the default keys were strings as well as QNames
+ MK: Becomes a bit messy.
+ JLO: Serialization options has both strings and QNames

Proposal: accept this PR.

Accepted.

** PR #2533: 2528 Update RFC reference (7159 -> 8259) for JSON 
:PROPERTIES:
:CUSTOM_ID: pr-2533
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2533][#2533]].

+ MK: Pretty trivial, as JSON spec has moved on with no appreciable material change.
     Minor editorial changes.
+ AP: It's now a real rather than proposed standard. Agreed with ECMA and IETF. 
     (Talked about this at 2024 Prague)
+ MK: Some small additions/changes in F&O regarding BOM etc.

Proposal: accept this PR.

Accepted.

** PR #2531: QT4CG-154-02 Revise rules for setting stylesheet parameters
:PROPERTIES:
:CUSTOM_ID: pr-2531
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2531][#2531]].

+ MK: Came from the proposal to add xsl:with-param to xsl:use-package.
  + … Revealed a bug in 3.0 where there was confusion about private and public parameter default visibilities
  + … More careful distinction between static and dynamic parameters in these cases.

Proposal: accept this PR.

Accepted.

** PR #2516: 2433 JTree function: Discuss JNode identity more fully
:PROPERTIES:
:CUSTOM_ID: pr-2516
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2516][#2516]].

+ MK: Address this issue at CG's request. A general set of notes about the identity of similar/same trees
  + … All we can say is that two trees with differing content have different identity.
  + … Not as strong a guarantee as we can give for XNodes
  + … Only important in cases with extractions for the same tree, including de-duplication
  + … Notes about where jtree() is call *implicitly*
     (Note context doesn't support much internal structure)
+ WP: Looks helpful. Having a JNode from a tree vs ???
+ JLO: Even though it is weakly defined, can I assume identical expressions on the same tree
     would produce the same identiies? What about via variables.
+ MK: An optimizer may have inlined the content of the variable, making several tree copies.
     OPtimizers aren't constrained not to expand in multiple places.

Proposal: accept this PR.

Accepted.

** 2.6a: PR #2551 - shadow attribute in a RNG schema
:PROPERTIES:
:CUSTOM_ID: pr-2551
:END:

+ MK: Don't really understand what it's trying to - not an RNG specialist. 
  + … NW might want to get involved. 
+ MK: I'll withdraw the PR and assign to NW.
+ WP: Willing to help NW with this. Needs validation.

PR #2551 will be abandoned.

** PR #2019: 1776: XSLT template rules for maps and array
:PROPERTIES:
:CUSTOM_ID: pr-2019
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2019][#2019]].

Not ready for discussion.

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:END:

None heard.
