:PROPERTIES:
:ID:       B58E1580-561A-4FEF-A955-AD665665A774
:END:
#+title: QT4 CG Meeting 170 Minutes 2026-06-30
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

[[../][Meeting index]] / [[https://qt4cg.org][QT4CG.org]] / [[https://qt4cg.org/dashboard][Dashboard]] / [[https://github.com/qt4cg/qtspecs/issues][GH Issues]] / [[https://github.com/qt4cg/qtspecs/pulls][GH Pull Requests]]

#+TOC: headlines 6

* Summary of new and continuing actions [0/9]
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: new-actions
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-167-01: DB to write a PR for #2641, comments in CSV
+ [ ] QT4CG-167-02: MK to make a PR for #2591, grammar for step?lookup is invalid
+ [ ] QT4CG-167-03: NW to make a PR for #2482, fallback on bin:decode-string
+ [ ] QT4CG-167-05: MK to write a proposal to change #2393 so the functions return JNodes
+ [ ] QT4CG-167-07: NW to review tests for interpolated strings with edge cases in mind
+ [ ] QT4CG-167-08: MK to review the state of #1949 to see which items are still outstanding.
+ [ ] QT4CG-167-09: NW to close all “nice to have” issues at the end of October if they haven’t progressed
+ [ ] QT4CG-170-01: RD to draft a proposal that attempts to address the lexical issues differently.

* Draft Minutes
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: minutes
:END:

Approved [[../2026/07-07.html][at meeting 171]] on 7 July 2026.

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:END:

** Roll call [11/11]
:PROPERTIES:
:CUSTOM_ID: roll-call
:END:

+ [X] David J Birnbaum (DB)
+ [X] Reece Dunn (RD)
+ [X] Christian Grün (CG)
+ [X] Joel Kalvesmaki (JK)
+ [X] Michael Kay (MK)
+ [X] Juri Leino (JLO)
+ [X] John Lumley (JWL)
+ [X] Alan Painter (AP)
+ [X] Wendell Piez (WP)
+ [X] Bethan Tovey-Walsh (BTW)
+ [X] Norm Tovey-Walsh (NW) /Scribe/. /Chair/.

** Accept the agenda
:PROPERTIES:
:CUSTOM_ID: agenda
:END:

Proposal: Accept [[../../agenda/2026/06-30.html][the agenda]].

Accepted.

** Approve minutes of the previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:END:

Proposal: Accept [[../../minutes/2026/06-23.html][the minutes of the previous meeting]].

Accepted.

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:END:

The next meeting is planned for 7 July.

No regrets heard.

** Review of open action items [1/9]
:PROPERTIES:
:CUSTOM_ID: open-actions
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-167-01: DB to write a PR for #2641, comments in CSV
+ [ ] QT4CG-167-02: MK to make a PR for #2591, grammar for step?lookup is invalid
+ [ ] QT4CG-167-03: NW to make a PR for #2482, fallback on bin:decode-string
+ [X] QT4CG-167-04: NW to make a PR explaining load-xquery-module for PR #2464
  + Overtaken by events; MK did it!
+ [ ] QT4CG-167-05: MK to write a proposal to change #2393 so the functions return JNodes
+ [ ] QT4CG-167-07: NW to review tests for interpolated strings with edge cases in mind
+ [ ] QT4CG-167-08: MK to review the state of #1949 to see which items are still outstanding.
+ [ ] QT4CG-167-09: NW to close all “nice to have” issues at the end of October if they haven’t progressed

** Review of open pull requests and issues
:PROPERTIES:
:CUSTOM_ID: open-pull-requests
:END:

This section summarizes all of the issues and pull requests that need to be
resolved before we can finish. See [[#technical-agenda][Technical Agenda]] below for the focus of this
meeting.

*** Blocked
:PROPERTIES:
:CUSTOM_ID: blocked
:END:

The following PRs are open but have merge conflicts or comments which
suggest they aren’t ready for action.

+ PR [[https://qt4cg.org/dashboard/#pr-2638][#2638]]: 2632-6: cross-cutting consistency (automatically generated & reviewed)
+ PR [[https://qt4cg.org/dashboard/#pr-2637][#2637]]: 2632-5: refresh stale 4.0 content (automatically generated & reviewed)
+ PR [[https://qt4cg.org/dashboard/#pr-2636][#2636]]: 2632-4: logic and semantics (automatically generated & reviewed)
+ PR [[https://qt4cg.org/dashboard/#pr-2635][#2635]]: 2632-3: typos and grammar (automatically generated & reviewed)
+ PR [[https://qt4cg.org/dashboard/#pr-2634][#2634]]: 2632-2: fix broken examples in expressions.xml (automatically generated & reviewed)
+ PR [[https://qt4cg.org/dashboard/#pr-2633][#2633]]: 2632-1: fix critical bugs and DTD-validity issues (automatically generated & reviewed)
+ PR [[https://qt4cg.org/dashboard/#pr-2594][#2594]]: 2389 Adaptive Serialization: more freedom
+ PR [[https://qt4cg.org/dashboard/#pr-2350][#2350]]: 708 An alternative proposal for generators
+ PR [[https://qt4cg.org/dashboard/#pr-2247][#2247]]: 716 Deferred Evaluation in XPath - the f:generator record
+ PR [[https://qt4cg.org/dashboard/#pr-2160][#2160]]: 2073 data model changes for JNodes and Sequences
+ PR [[https://qt4cg.org/dashboard/#pr-2071][#2071]]: 77c deep update

*** Merge without discussion
:PROPERTIES:
:CUSTOM_ID: merge-without-discussion
:END:

The following PRs are editorial, small, or otherwise appeared to be
uncontroversial when the agenda was prepared. The chairs propose that
these can be merged without discussion. If you think discussion is
necessary, please say so.

+ PR [[https://qt4cg.org/dashboard/#pr-2732][#2732]]: 2708 Obsolete references to maps being unordered
+ PR [[https://qt4cg.org/dashboard/#pr-2711][#2711]]: 2536 EXPath modules: handling of default values
+ PR [[https://qt4cg.org/dashboard/#pr-2701][#2701]]: 2677 Clarify effect of serialization-params on fn:transform

Proposal: merge without discussion.

Accepted.

*** Close without action
:PROPERTIES:
:CUSTOM_ID: close-without-action
:END:

It has been proposed that the following issues be closed without action.
If you think discussion is necessary, please say so.

+ Issue [[https://github.com/qt4cg/qtspecs/issues/2464][#2464]]: add method to use path()

Proposal: close with no further action

Accepted.

*** Substantive PRs
:PROPERTIES:
:CUSTOM_ID: substantive
:END:

The following substantive PRs were open when this agenda was prepared.

+ PR [[https://qt4cg.org/dashboard/#pr-2736][#2736]]: 2169 Reformulate `StringInterpolation` to remove the `` `{ `` and `` }` `` literal terminals
+ PR [[https://qt4cg.org/dashboard/#pr-2734][#2734]]: 2733 A step too far
+ PR [[https://qt4cg.org/dashboard/#pr-2731][#2731]]: 2709 Well-formed sub-documents (2nd attempt)
+ PR [[https://qt4cg.org/dashboard/#pr-2719][#2719]]: 1234 Serialization Parameters: Indentation, Whitespace, Newlines
+ PR [[https://qt4cg.org/dashboard/#pr-2717][#2717]]: 2660 fn:matching-segments: named capture groups
+ PR [[https://qt4cg.org/dashboard/#pr-2715][#2715]]: 2653 FLWOR, member/key/value clauses: allow sequences
+ PR [[https://qt4cg.org/dashboard/#pr-2714][#2714]]: 2219 Generalize method calls to sequences
+ PR [[https://qt4cg.org/dashboard/#pr-2713][#2713]]: 2257 Record declarations without namespace
+ PR [[https://qt4cg.org/dashboard/#pr-2712][#2712]]: 2702 Dynamic node tests
+ PR [[https://qt4cg.org/dashboard/#pr-2710][#2710]]: 2702 Dynamic selectors: focus-dependency
+ PR [[https://qt4cg.org/dashboard/#pr-2707][#2707]]: 1962 fn:map-to-element
+ PR [[https://qt4cg.org/dashboard/#pr-2706][#2706]]: 2704 change path() output for JNodes
+ PR [[https://qt4cg.org/dashboard/#pr-2698][#2698]]: 2641 Support comments in csv
+ PR [[https://qt4cg.org/dashboard/#pr-2696][#2696]]: 2695 Apply templates to maps, arrays, and JNodes
+ PR [[https://qt4cg.org/dashboard/#pr-2649][#2649]]: 2647 file:descendants: recursion, filtering
+ PR [[https://qt4cg.org/dashboard/#pr-2739][#2739]]: 2738 XSLT - tree terminology

* Technical agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:END:

** PR #2736: 2169 Reformulate `StringInterpolation` to remove the `` `{ `` and `` }` `` literal terminals
:PROPERTIES:
:CUSTOM_ID: pr-2736
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2736][#2736]]

+ CG: I asked Gunther to create the PR.
+ RD: I don’t think Gunther’s proposal is the correct one that resolves the underlying issue.
  + … I think the underlying issue is in how we’re describing the tokenization rules.
  + … Perhaps we should reformulate this by grouping the parser constructs by the logical construct they define
    + … There are two grammar rules for comments, for example. Do something similar for string interpolation, etc.
  + … Then pull in some of the logic from the old tokenizer draft. Describe it how the HTML5 rules work.
    + … If you find this token, then transition to this state, etc.
    + … Then it would be clearer what characters a valid in which states.
  + … I think all the XQuery parsers are using some sort of state-based parsing.
+ MK: We need to keep the specification distinct from an implementation. HTML
  has gone down the route of putting an implementation in the spec and I think
  that’s a disaster.
  + … We need to keep things more abstract.
+ RD: What I’m proposing wouldn’t constrain implementations. An implementation
  could use a state based lexer, or they could drive it by the current parse
  context or…
+ MK: The problem with the HTML approach is that bugs in the spec become bugs in the implementation.
  + … If the state tables are wrong, you have to implement them incorrectly to be conformant.
+ RD: I think what I’m suggesting is to group the rules and describe the lexical
  states that enter and exit those groups.
  + … I’m not suggesting a specific implementation, I’m proposing organizing things differenty.
  + … Something between what we have now and the HTML rules, but in an implementation-flexible way.
  + … One of the difficulties is that because of the complexities of tokenizing
    and parsing XQuery and XPath, you need to document some of this otherwise it’s unclear what the behavior is.
+ JLO: I do like the idea of splitting up the grammar differently. I don’t think
  that it necessarily requires a particular implementation.
  + … I fail to see the problem, but Gunther showed me.
+ RD: I’m willing to experiment and try to see what this looks like.
+ MK: It needs a concrete proposal.
+ JLO: We all agree that there is a problem.
+ MK: I’m not convinced that there’s a problem after we apply Gunther’s patch.
+ JLO: ~ws:explicit~ isn’t a problem?
+ MK: I expect that could use a bit more explanation of exactly what that means.
+ RD: I’m not convinced because I find the wording of the note on “complex terminals” confusing, as I said in a comment on the PR.
  + … That’s around the tokenization of the processing instruction. From the
    wording there, it seems to imply that if you’ve got a preprocessing literal
    inside the content of a string interpolation, then by the longest token
    rules, and because the tokenization rules aren’t context dependent with
    these changes, then that should be processed as a preprocessed literal
    rather than a string interpolation content.
+ NW: We don’t seem to have consensus…
+ MK: Are you sure? Gunther’s PR improves the situation.

Proposal: accept this PR.

Accepted.

ACTION QT4CG-170-01: RD to draft a proposal that attempts to address the lexical issues differently.

** PR #2734: 2733 A step too far
:PROPERTIES:
:CUSTOM_ID: pr-2734
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2734][#2734]]

+ MK: The proposal we accepted to treat any step that yields an atomic value as
  a selection, was going to far: it leads to some undesirable consequences.
  + … Let’s look at the proposal and then discuss some of the alternatives.

MK walks through the PR.

+ MK: If you’re in the context of JNodes, any step that returns atomic values
  was being interpreted as a selector. So you got a sort of double-evaluation if
  you put ~jvalue()~ after a slash.
  + … What I propose here is that we should only treat ~E2~ in ~E1/E2~ as a selector
    if it’s a literal or variable reference.
  + … All other expressions, whether they return atomic values or nodes are
    treated as mapping expressions.
  + … It’s not referentially transparent, unfortunately.
  + … As soon as you put in an expression instead of a literal, it means something else.

+ MK: One other alternative depends on deciding if an expression was context
  sensitive. But that’s hard to do.

On other possible formulation is in the comments on the PR.

+ MK: We can decide if an expression is “navigational” or not, with some rules.
  And we do the rewrite for ~E2~ only if it *isn’t* navigational.
  + … If it is navigational, but doesn’t return JNodes then it throws an error.
  + … That means using ~!~ or ~=!>~ instead of ~/~ in some cases.
+ MK: It’s still a bit arbitrary, but it seems like it gives better results.
  + … Basically ~/~ has two meanings: it’s either navigational or a selector.

+ WP: Am I right that this would expose all my bad habits and make me fix them?
+ MK: No, but you won’t be able to carry your bad habits over into JNodes.
  + … It’s fully backwards compatible with XNodes
+ WP: With respect to JNodes it means we have a different classification rather than an anomaly.
+ JLO: This is only if I want to output a literal, I have to use ~!~
+ MK: Yes. We’re also discouraging you from writing ~…/function()~ where that
  function computes a value rather than navigating.

Some discussion of paths ending with ~/string()~ or ~/data()~.

+ JLO: If it really is about ~string()~ and ~data()~, we should make that more prominent.
+ RD: For an existing 3.1 expression using XML nodes, it works as is.
+ WP: It seems to me that the underlying issue is a feature of the transparency:
  JNodes work like XNodes except when they don’t.

+ CG: From a technical point of view, I definitely like the simpler proposal.
  + … We already have similar situations like constant strings in predicates.
  + … Regarding the two proposals: the existing one or navigation one. I think
    the navigational one will cause fewer surprises.
  + … With the first proposal, you’ll get different results depending on whether
    you use single or double quotes or back ticks.

+ MK: Okay, I’ll try to develop the navigational approach into a proposal.

** PR #2731: 2709 Well-formed sub-documents (2nd attempt)
:PROPERTIES:
:CUSTOM_ID: pr-2731
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2731][#2731]]

This is purely editorial. MK observes that something seems to have gone wrong
with the commit as it’s incomplete.

MK to update the PR so that it has all of the files.

** PR #2719: 1234 Serialization Parameters: Indentation, Whitespace, Newlines
:PROPERTIES:
:CUSTOM_ID: pr-2719
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2719][#2719]]

+ CG: There are a lot of implementation dependent ways to specify things like indentation width.
  + … I thought it might be good to try to formalize this.

CG describes the new parameters: ~indent-unit~, ~indent-attributes~, and ~line-ending~.

+ JWL: Will you get line endings without indentation? I can see a case where you
  get some extraordinarily deep trees, you might want the ident-unit to be empty
  or a single character. I’d be happy for the algorithm to be adaptive.
+ CG: Line endings will always be output.
+ JWL: So if you don’t turn on indentation, you’ll still get all the tags on different lines?
+ CG: No, then it would be everything on one line.
+ JWL: That’s my argument for allowing the indent-unit to be the empty string.
+ CG: I can change that.
+ MK: Three comments: 
  + … Why is this only for the XML output method, rather than for XHTML and JSON etc. I think we’d want to apply it to all of them.
  + … The proposal needs to cover all the wretched different ways to set serialization parameters in XSLT and XQuery.
  + … From a usability perspective: how are we going to present these values in
    the attributes. Requiring explicit backslash t and backslash s might be the
    way to do it.
    + … We’ve introduced those in the ~char()~ function. I’d suggest doing it that way.
+ CG: I think that we could use the backslash forms in some of the cases.
+ MK: We can limit it to what survives round tripping in XML.
+ CG: I should add it to HTML and XHTML.
+ JLO: I’m confused about the discussion of backslash t and U+0009? Is there an example?
+ CG: I think it would be something like ~\t\t~ and ~\r\n~ (etc) for the values that are represented.
+ JLO: And not entities? That’s confusing.
+ MK: Entities are fine in XML, but what if you then get the serialization
  parameters from a JSON document, what do you write there?
+ JLO: This would be a hard sell for me.
+ MK: We could just use ~t~ ~s~ ~r~ and ~n~.
+ JLO: What about using a zero-width characters?
+ MK: And they aren’t treated as whitespace by an XML parser.
+ JLO: Ok, nevermind then.
+ CG: We could allow three constants and then if the input isn’t one of those
  constants, we could use the input as a literal string.

** PR #2717: 2660 fn:matching-segments: named capture groups
:PROPERTIES:
:CUSTOM_ID: pr-2717
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2717][#2717]]

CG introduces the PR.

+ CG: The ~fn:matching-segment~ function returns numbered groups. The idea is
  that we should allow names as many other languages do.

CG jumps to the example that shows year, month, day instead of 1, 2, 3.

+ CG: I’ve limited the names to ASCII literals. You get only the names if you
  use names. The names must be distinct.
+ MK: I like it, apart from the fact that it’s more work.
  + … I do think we need to carry it through into the replace function.
+ CG: Yep. I’ve created an issue for that and will do it next.
+ JK: In one of my comments, I observed that a named capturing group will not also have an integer index value.
  + … If you have a named group but you also want to refer to it by number, what behavior do you expect.
+ CG: My first proposal included the group number, but that’s redundant. You can
  also have groups that aren’t part of the match, so the numbers are not always
  consecutive.
+ MK: I thought it was preferable not to have the redundancy, but I don’t feel strongly about it.
+ JLO: I think that if a named capturing group that can occur more than once,
  you might want to find them by number.
  + … I haven’t seen it in the wild, but it seems possible.
+ CG: I can also check what other languages provide.
+ WP: Are we also going to have named groups for ~xsl:analyze-string~?
+ CG: Yes, I did that in ~xsl:analyze-string~ as well.
+ JK: The other question I asked, will there be any potential pitfalls if someone attempts to name the groups with integers.
+ CG: The group names will be strings.

Some discussion of how lookup expressions work.

+ CG: Also, at the moment, digits aren’t allowed at the beginning.
+ BTW: I’m wondering about making group names ASCII letters and digits.
  + … Does this disadvantage people who are working in non-latin languages.
+ WP: Probably not more than they are already disadvantaged.

Some discussion of ASCII vs any Unicode name character.

+ WP: That’s why I try to use XML Names in this place.
+ MK: Have we abandoned the idea that this should be implemented with third party libraries.


* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:END:

None heard.


