:PROPERTIES:
:ID:       8D64117B-C257-4FF3-AF21-E245DD91939D
:END:
#+title: QT4 CG Meeting 173 Minutes 2026-07-21
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

[[../][Meeting index]] / [[https://qt4cg.org][QT4CG.org]] / [[https://qt4cg.org/dashboard][Dashboard]] / [[https://github.com/qt4cg/qtspecs/issues][GH Issues]] / [[https://github.com/qt4cg/qtspecs/pulls][GH Pull Requests]]

#+TOC: headlines 6

* Summary of new and continuing actions [0/6]
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: new-actions
:ID:       E163C5FF-35A6-42C7-97C1-26018A7A55D1
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-167-03: NW to make a PR for #2482, fallback on bin:decode-string
+ [ ] QT4CG-167-05: MK to write a proposal to change #2393 so the functions return JNodes
+ [ ] QT4CG-167-07: NW to review tests for interpolated strings with edge cases in mind
+ [ ] QT4CG-167-09: NW to close all “nice to have” issues at the end of October if they haven’t progressed
+ [ ] QT4CG-170-01: RD to draft a proposal that attempts to address the lexical issues differently.

* Draft Minutes
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: minutes
:ID:       0BDB88A2-D60E-4433-989D-7C30746646D1
:END:

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:ID:       F0ED304A-B587-4287-BF0F-CDE26E92E3BE
:END:

** Roll call [9/11]
:PROPERTIES:
:CUSTOM_ID: roll-call
:ID:       7815DDD1-075E-4C88-9A31-FD67706BCBC0
:END:

BTW gives regrets.

+ [X] David J Birnbaum (DB)
+ [ ] Reece Dunn (RD)
+ [X] Christian Grün (CG)
+ [X] Joel Kalvesmaki (JK)
+ [X] Michael Kay (MK)
+ [X] Juri Leino (JLO)
+ [X] John Lumley (JWL)
+ [X] Alan Painter (AP)
+ [X] Wendell Piez (WP)
+ [ ] Bethan Tovey-Walsh (BTW)
+ [X] Norm Tovey-Walsh (NW) /Scribe/. /Chair/.

** Accept the agenda
:PROPERTIES:
:CUSTOM_ID: agenda
:ID:       9E01AE79-8B33-4350-A30B-0434746BB39C
:END:

Proposal: Accept [[../../agenda/2026/07-21.html][the agenda]].

Accepted.

** Approve minutes of the previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:ID:       3C647E5A-D1C7-4827-B402-82AF780C4C27
:END:

Proposal: Accept [[../../minutes/2026/07-14.html][the minutes of the previous meeting]].

Accepted.

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:ID:       8AB5EF3E-FFE6-4BE5-9EC6-FB0C5D9FFFB1
:END:

The next meeting is planned for 28 July. We will not meet on 4 August.

JLO gives regrets; possible regrets from JWL.

** Review of open action items [3/9]
:PROPERTIES:
:CUSTOM_ID: open-actions
:ID:       AD7E58EB-760F-427C-93D2-A6F2ADF2D7AA
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [X] QT4CG-167-02: MK to make a PR for #2591, grammar for step?lookup is invalid
  + Overtaken by events.
+ [ ] QT4CG-167-03: NW to make a PR for #2482, fallback on bin:decode-string
+ [ ] QT4CG-167-05: MK to write a proposal to change #2393 so the functions return JNodes
+ [ ] QT4CG-167-07: NW to review tests for interpolated strings with edge cases in mind
+ [X] QT4CG-167-08: MK to review the state of #1949 to see which items are still outstanding.
  + Overtaken by events
+ [ ] QT4CG-167-09: NW to close all “nice to have” issues at the end of October if they haven’t progressed
+ [ ] QT4CG-170-01: RD to draft a proposal that attempts to address the lexical issues differently.
+ [X] QT4CG-172-01: MK to check if the XSLT rules are consistent with the rules in #2757.
  + Nothing to do in XSLT.
g
* Technical agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:ID:       1DADB821-F041-4D37-A014-02B6FC0A639C
:END:

This week, I’ve put the oldest ones first, but we might decide to skip over some of them.

** PR #2594: 2389 Adaptive Serialization: more freedom
:PROPERTIES:
:CUSTOM_ID: Technical_agenda-PR_#2594:_2389_Adaptive_Serialization:_more_freedom-B82DDEC3
:ID:       47F64278-FC16-4795-97F4-126DCC0D7649
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2594][#2594]].

CG reviews the changes based on feedback.

+ CG: I changed the rules for strings to make it implementation
  defined how “&” is encoded. (So that it can be XPath or XQuery
  compatible.)
+ CG: I made the rules for numerics more liberal.
  + … Mostly for JSON.
+ CG: Changed QName notation to allow prefixes for various statically known namespaces.
  + … Added a rule that an implementation can include additional prefixes.
+ CG: Implementation defined whether the enclosing quote characters need to be included.
+ CG: In a nutshell, it allows processors to be more liberal.
+ JWL: I like the approach. When I’m debugging, I use mixtures of arrays and maps and trees and I have to serialize them.
+ AP: Why implementation-dependent instead of having options?
+ CG: I think it would become too complex if you tried to add options for all of the possible choices.
+ AP: I fear that this might get tricky.
+ JLO: I like this. I see that an implementation is still allowed to
  output a top-level string unquoted, so it would be impossible to
  read it back in.
+ CG: Yes.
+ JLO: Why?
+ CG: Maybe this is related to the options AP mentioned. We use this
  kind of serialization for debugging and for copying and pasting
  code. Strings for users other than XQuery users want the unquoted string!
  + … We haven’t decided how to offer these options.
+ DB: Is there a difference between implementation defined and implementation dependent.
+ CG: Defined means that you need to document the choices.

Some discussion of how implementation-defined features sometimes fail to get documented.

Proposal: accept this PR.

Accepted.

** PR #2696: 2695 Apply templates to maps, arrays, and JNodes
:PROPERTIES:
:CUSTOM_ID: Technical_agenda-PR_#2696:_2695_Apply_templates_to_maps,_arrays,_and_JNodes-EFA11EDD
:ID:       592D4549-0A0C-4206-8443-1C688CD54287
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2696][#2696]].

+ MK: This is all XSLT.
  + … It’s filling in the gaps about what apply-templates does when there’s no select attribute.
  + … It’s a step along the journey to defining a complete story for applying templates to maps and arrays.
+ MK: It doesn’t change the meaning of ~xsl:apply-templates~ if there is a ~select~ attribute; only if its absent.
  + … If there’s no ~select~, then we change it so that it doesn’t only use the child axis.

MK reviews the changed prose.

+ JWL: Looking at the rules, if it’s a JNode, then you go to the
  children. If it’s a map or array that isn’t a JNode, you make a tree
  from that point on.
  + … Does that mean in one case you can reach into the ancestors and in the other case you can’t?
+ MK: Yes. If you’re starting at a JNode, then the ancestors are available. If you’re starting at a map or array, then you start a new tree.
+ JK: I don’t understand and I don’t really like the rule about what to do with atomic values. It invites infinite regression.
  + … I’d prefer to have it do nothing in that case. Currently, that fourth rule is asymmetric with the others.
+ MK: Yes. I share the concerns. I wrote some examples and found myself writing a lot of ~select="."~ so why isn’t that the default?
  + … But it tended to be in a for each. But I can see the concern.
+ WP: I share the concern too. It’s the kind of thing that can bite you when you don’t expect it, especially if you’re a little naive.
  + … My question was about the rationale, but I think you’ve explained that.
  + … This seems like a bad bug to have to debug as a beginner.
  + … I’d think about reconsidering whether this should do nothing or be an error.

MK will reconsider.

** PR #2707: 1962 fn:map-to-element
:PROPERTIES:
:CUSTOM_ID: Technical_agenda-PR_#2707:_1962_fn:map-to-element-E69118A2
:ID:       59AEF873-024B-44AD-8823-2F9A79280986
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2707][#2707]].

+ CG: I think we should skip it today. It’s supposed to be the inverse
  of ~fn:element-to-map~, but it could lead to a lot of discussion.

Everyone, please review.

** PR #2712: 2702 Dynamic node tests
:PROPERTIES:
:CUSTOM_ID: Technical_agenda-PR_#2712:_2702_Dynamic_node_tests-07154989
:ID:       F462976F-E77C-483A-9246-68573E0A7F6A
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2712][#2712]].

+ MK: We had the syntax before, but we didn’t have a name for them. This gives them a name in the grammar and the prose.
  + … And it refines the semantics.
+ MK: In ~NodeTest~, we add a new name ~DynamicNodeTest~ to hang semantics on.
  + … It’s an ~EnclosedExpr~ so there’s no substantive change to the grammar.

MK reviews the revised semantics.

+ MK: Typical usage is ~child::{"date of birth"}~.
+ MK: ~child::{1 to 3}~ and ~child::{3, 2, 1}~ are the same, you always get document order.

Proposal: accept this PR.

Accepted.

** PR #2714: 2219 Generalize method calls to sequences
:PROPERTIES:
:CUSTOM_ID: Technical_agenda-PR_#2714:_2219_Generalize_method_calls_to_sequences-6BD9D433
:ID:       DBB3DA54-9E65-4814-B8D5-19B245BF6DA6
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2714][#2714]].

+ CG: This one and the next PR are about sequences.
  + … We’ve recently decided that a dynamic function call will work on sequences.
  + … So now you can have a sequence of functions and invoke them.
+ CG: This extension does the same thing for method calls (~=?>~ syntax).
  + … If the sequence is empty, it works like paths and lookups and returns the empty sequence.
+ MK: I’m not enthusiastic, but I won’t stand in the way.
+ JLO: Was there an example?

CG does an example interactively.

+ JLO: I see a lot of foot gun potential.
+ CG: Do we want to have a sequence of function items and invoke them.

+ MK: This comes up when you have a path expression. Everything else works on sequences.
  + … ~a/b/c~ always allow sequences and apply the results across the sequence
  + … You don’t want to break that if you’re selecting functions.

+ JLO: Was this born out of JNodes?
+ MK: In many ways its more related to the fact that maps are functions.
+ JLO: But if ~()()~ works, then I can call any key on a function? 
+ CG: At least with a record, the key will be rejected according to the new rules.
+ MK: Static type checking allows you to reject cases where you would be trying to invoke a function.
+ CG: ~{}?z()~ would be legal.
+ JLO: We could also say that a record method can only be a single function item.
+ CG: True.
+ MK: But then you’d have to look at the effect of that in a pipeline.
  + … With multiple ~/~ and ~->~ operators.

Proposal: accept this PR.

Accepted.

** PR #2715: 2653 FLWOR, member/key/value clauses: allow sequences
:PROPERTIES:
:CUSTOM_ID: Technical_agenda-PR_#2715:_2653_FLWOR,_memberkeyvalue_clauses:_allow_sequences-2FAE0374
:ID:       4B2F9A35-908E-4996-82B2-0EF56BD62391
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2715][#2715]].

+ CG: This one is about sequences. I claim this one is also about consistency.
  + … It can happen that when you’re iterating over the keys and
    values in a map that you get an error because there’s an empty map
    so an empty sequence.
+ MK: You’re processing all the entries in one map first, then all the entries in the second?
+ CG: Yes.

Proposal: accept this PR.

Accepted.

** PR #2719: 1234 Serialization Parameters: Indentation, Whitespace, Newlines
:PROPERTIES:
:CUSTOM_ID: Technical_agenda-PR_#2719:_1234_Serialization_Parameters:_Indentation,_Whitespace,_Newlines-E76B440D
:ID:       558E84A5-7EF0-4CFE-97EB-74BB81D6EC15
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2719][#2719]].

+ CG: We’ve talked about this one before. I’ve tried to incorporate the latest comments.
  + … We’ve already discussed the names and types of the options.
  + … I should add some examples for ~(\t|\\t)*| *~.
  + … The same rules apply to line endings.
+ CG: The remaining rules are the same.

CG reviews the questions in the PR.

+ WP: I think this flashed by. We now support a line feed with no indent?
+ CG: Yes.
+ JLO: The zero indent is because you’re allowed to have nothing in the indent parameter.
+ CG: Yes.
+ MK: Observation about the XSLT end of things. The values get put in
  attributes of ~xsl:output~ or ~xsl:result-document~. It’s really not
  very practical to put newlines and tabs in attributes.
  + … In theory you can write them as entities, but it’s tricky.
  + … What’s the best way to represent these in XSLT? Maybe limit it to the backslash forms.
+ JWL: Echoing MK’s concern. What about if you put in spaces, could you use ~\s~?
+ MK: I think a visual representation is preferable.

Some discussion of when and where it’s helpful to have zero indentation but have line endings.
Further discussion of how it interacts with ~suppress-indentation~. 

+ MK: That’s for inline markup where you don’t want any whitespace at all.

Proposal: accept this PR.

Accepted.

** PR #2800: 2799 fn:slice: negative steps
:PROPERTIES:
:CUSTOM_ID: Technical_agenda-PR_#2800:_2799_fn:slice:_negative_steps-15FB69E7
:ID:       D6180082-B8A9-4047-9931-C7A01E3DE595
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2800][#2800]].

+ CG: A user observed that ~fn:slice~ with a negative step works like reverse.
+ CG: I added some rules to clarify that.
+ MK: I had to think fairly hard but came to the conclusion that it worked.

Proposal: accept this PR.

Accepted.

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:ID:       18692478-847C-4598-9E52-B93663287FF0
:END:

None heard.

