:PROPERTIES:
:ID:       8E3D5F18-FC95-412C-B888-31C42680622D
:END:
#+title: QT4 CG Meeting 174 Minutes 2026-07-28
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

[[../][Meeting index]] / [[https://qt4cg.org][QT4CG.org]] / [[https://qt4cg.org/dashboard][Dashboard]] / [[https://github.com/qt4cg/qtspecs/issues][GH Issues]] / [[https://github.com/qt4cg/qtspecs/pulls][GH Pull Requests]]

#+TOC: headlines 6

* Summary of new and continuing actions [0/7]
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: new-actions
:ID:       E163C5FF-35A6-42C7-97C1-26018A7A55D1
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-167-03: NW to make a PR for #2482, fallback on bin:decode-string
+ [ ] QT4CG-167-05: MK to write a proposal to change #2393 so the functions return JNodes
+ [ ] QT4CG-167-07: NW to review tests for interpolated strings with edge cases in mind
+ [ ] QT4CG-167-09: NW to close all “nice to have” issues at the end of October if they haven’t progressed
+ [ ] QT4CG-170-01: RD to draft a proposal that attempts to address the lexical issues differently.
+ [ ] QT4CG-174-01: MK to make an issue or otherwise address CG’s comments on #2734.

* Draft Minutes
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: minutes
:ID:       0BDB88A2-D60E-4433-989D-7C30746646D1
:END:

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:ID:       F0ED304A-B587-4287-BF0F-CDE26E92E3BE
:END:

** Roll call [9/11]
:PROPERTIES:
:CUSTOM_ID: roll-call
:ID:       7815DDD1-075E-4C88-9A31-FD67706BCBC0
:END:

JLO gives regrets.

+ [X] David J Birnbaum (DB)
+ [ ] Reece Dunn (RD)
+ [X] Christian Grün (CG)
+ [X] Joel Kalvesmaki (JK)
+ [X] Michael Kay (MK)
+ [ ] Juri Leino (JLO)
+ [X] John Lumley (JWL)
+ [X] Alan Painter (AP)
+ [X] Wendell Piez (WP)
+ [X] Bethan Tovey-Walsh (BTW)
+ [X] Norm Tovey-Walsh (NW) /Scribe/. /Chair/.

** Accept the agenda
:PROPERTIES:
:CUSTOM_ID: agenda
:ID:       9E01AE79-8B33-4350-A30B-0434746BB39C
:END:

Proposal: Accept [[../../agenda/2026/07-28.html][the agenda]].

Accepted.

** Approve minutes of the previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:ID:       3C647E5A-D1C7-4827-B402-82AF780C4C27
:END:

Proposal: Accept [[../../minutes/2026/07-21.html][the minutes of the previous meeting]].

Accepted.

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:ID:       8AB5EF3E-FFE6-4BE5-9EC6-FB0C5D9FFFB1
:END:

The next meeting is planned for 11 August. We will not meet on 4 August.

AP gives regrets.

** Review of open action items [0/6]
:PROPERTIES:
:CUSTOM_ID: open-actions
:ID:       AD7E58EB-760F-427C-93D2-A6F2ADF2D7AA
:END:

The action item list in the agenda was incorrect.

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-167-03: NW to make a PR for #2482, fallback on bin:decode-string
+ [ ] QT4CG-167-05: MK to write a proposal to change #2393 so the functions return JNodes
+ [ ] QT4CG-167-07: NW to review tests for interpolated strings with edge cases in mind
+ [ ] QT4CG-167-09: NW to close all “nice to have” issues at the end of October if they haven’t progressed
+ [ ] QT4CG-170-01: RD to draft a proposal that attempts to address the lexical issues differently.

** Review of open pull requests and issues
:PROPERTIES:
:CUSTOM_ID: open-pull-requests
:ID:       F0E0D18E-CDFE-4380-97AD-2A90A4EC3EDA
:END:

This section summarizes all of the issues and pull requests that need to be
resolved before we can finish. See [[#technical-agenda][Technical Agenda]] below for the focus of this
meeting.

*** Blocked
:PROPERTIES:
:CUSTOM_ID: blocked
:ID:       73807C65-9E0E-4006-999E-6562F4F8A375
:END:

The following PRs are open but have merge conflicts or comments which
suggest they aren’t ready for action.

+ PR [[https://qt4cg.org/dashboard/#pr-2071][#2071]]: 77c deep update
+ PR [[https://qt4cg.org/dashboard/#pr-2160][#2160]]: 2073 data model changes for JNodes and Sequences
+ PR [[https://qt4cg.org/dashboard/#pr-2247][#2247]]: 716 Deferred Evaluation in XPath - the f:generator record
+ PR [[https://qt4cg.org/dashboard/#pr-2350][#2350]]: 708 An alternative proposal for generators
+ PR [[https://qt4cg.org/dashboard/#pr-2768][#2768]]: 2740 Drop constructor functions from built-in records

*** Merge without discussion
:PROPERTIES:
:CUSTOM_ID: merge-without-discussion
:ID:       053CE6E2-CF6B-462F-99CB-75B063D2866F
:END:

The following PRs are editorial, small, or otherwise appeared to be
uncontroversial when the agenda was prepared. The chairs propose that
these can be merged without discussion. If you think discussion is
necessary, please say so.

+ PR [[https://qt4cg.org/dashboard/#pr-2804][#2804]]: 2780 Functions on CSV Data: comments
+ PR [[https://qt4cg.org/dashboard/#pr-2803][#2803]]: 2773 fn:hash: wording
+ PR [[https://qt4cg.org/dashboard/#pr-2792][#2792]]: 2790 fn:pad-string, truncation

Proposal: merge these issues without discussion.

Accepted.

* Technical agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:ID:       1DADB821-F041-4D37-A014-02B6FC0A639C
:end:

I’m putting the oldest ones first, again this week. I don’t imagine we’ll get through all of them.

** PR #2696: 2695 Apply templates to maps, arrays, and JNodes
:PROPERTIES:
:CUSTOM_ID: pr-2696
:ID:       1D5F2E5F-5377-4C46-A3C8-B8C8B64AC3EA
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2696][#2696]]

+ MK: I updated it as requested last week. It’s an error to omit the ~select~
  attribute if the content is not an array, map, or element.
+ WP: So it works like it does now and you can use strings but you have to use select.
+ MK: Yes.

Proposal: accept this PR.

Accepted.


** PR #2707: 1962 fn:map-to-element
:PROPERTIES:
:CUSTOM_ID: pr-2707
:ID:       BC46D0C3-957E-49E2-A228-3F8E7EDCCA7C
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2707][#2707]]

Skip this again this week.

** PR #2719: 1234 Serialization Parameters: Indentation, Whitespace, Newlines
:PROPERTIES:
:CUSTOM_ID: pr-2719
:ID:       CCB5ABE9-3F27-4A5F-97CA-6C19F9F44E36
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2719][#2719]]

Resolved and merged.

** PR #2734: 2733 A step too far
:PROPERTIES:
:CUSTOM_ID: pr-2734
:ID:       CCC274D4-3CC8-473D-81DE-7538905EF12F
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2734][#2734]]

+ MK: We reviewed an earlier draft, but folks weren’t too happy. So I’ve revised it.
+ MK: The background is making expressions like ~$map/2~ work when you’re dealing with JNodes.
  + … The previous proposal said you get the special treatment of child selection only for literals and variable references.
  + … People weren’t too happy with that.
  + … This takes the opposite approach, you get the behavior *unless* the expression is one of a set of navigation expressions.

MK reviews the definition of /navigational/ steps in the specification.

+ MK: For ~E1/E2~, for an XNode, we evaluate it as before.
+ MK: For JNodes, we say the results are similar, provided that the steps are navigational.
  + … In call cases, the result will consist of JNodes.
  + … Where ~E2~ is non-navigational, the value of ~E2~ is used as a map key or array subscript.
  + … It’s evaluated with out a context, so it’s an error to refer to the context.
  + … If you want a step that does that, you need to use something else, like ~!~.
  + … This allows ~$booklist/$category//author/1/"last name"~.
  + … Then we provide an analogy to make it clear what the semantics mean.
+ MK: Essentially, navigational expressions are ones that depend on the focus,
  but that doesn’t generalize to all the function calls.
+ MK: There’s a lack of referential transparency, but it does what you think it will if you don’t think too hard.
+ JWL: What if you have maps that contain a mixture of maps and XNode trees.
  + … Suppose I want to write an expression that says “find a map entry called
    “name” which is such and such” and from there, I want to got back up and
    down into the “tree” entry using XNode matching.
+ MK: You can do that, but you have to extract the value out of the JNode.
+ JWL: So I get a sequence that comes down to ~!~ that does a ~jvalue()~ and then I’m back to XNodes
  + … It might be worth explaining what happens with mixtures.
+ CG: I like the proposal. I think it’s a good compromise. I put some comments in the PR.
+ MK: Let’s look.
+ CG: Do we need to have a sequence of XNodes or JNodes or could they be mixed? I think they could be mixed.
+ MK: It makes life more and more difficult to decide evaluation statically, but that’s already not always possible.
+ CG: The next is that ~*~ needs to be replaced with ~gnode()~.
+ CG: And there are some attributes missing.
+ CG: And could we add try/catch?
+ MK: I’ll look at those comments.
+ WP: I like it. As far as I understand it, it looks workable. It’s going to be a lot easier to understand in the context of data.
  + … Worked examples, especially ones that show gotchas would be very helpful.
  + … Using variables is going to help users; some examples along those lines might be useful.

Some discussion of distinguishing between JNode and XNode with ~instance of~.

Proposal: Accept this PR.

Accepted.

ACTION QT4CG-174-01: MK to make an issue or otherwise address CG’s comments on #2734.

** PR #2739: 2738 XSLT - tree terminology
:PROPERTIES:
:CUSTOM_ID: pr-2739
:ID:       D2294C22-F857-4A3E-81A1-9D11EAC1E9EF
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2739][#2739]]

+ MK: This is a simple editorial change.
+ MK: Doing this comprehensively is too radical. What I decided to do was get
  the introduction and terminology sections correct and then try to bring other
  things in line as best we can.
  + … It makes various changes to the introduction to de-emphasise that it’s an
    XML transformation language.
+ MK: I’ve split the concepts and terminology sections so that
  conformance and implementation-related things are separate from technical terms.

Proposal: Accept this PR.

Accepted.

** PR #2760: 2521 URIs: unify handling of fragment identifiers
:PROPERTIES:
:CUSTOM_ID: pr-2760
:ID:       36900FC5-2794-469E-B3DC-AA563337BA9F
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2760][#2760]]

+ CG: This is mostly about consistency vs. progress. We want consistent behavior.
  + … To allow or disallow fragment identifiers for all of them.
  + … But #2786 may be blocking.
+ MK: Part of my concern is that very often the handling of URIs is handed off
  to an XML parser or bit of infrastructure, and we don’t always have control over them.
  + … We might not even know which parser is used and it’s not always under our
    control whether or not things like fragment identifiers are supported.
+ NW: Yes, but I think we should be consistent.

** PR #2777: 2644 Extend casts to sequences, arrays, maps, and records
:PROPERTIES:
:CUSTOM_ID: pr-2777
:ID:       E57DC187-FA4A-4BF5-B83C-F49EC1479AF4
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2777][#2777]]

+ MK: The motivation was primarily casting to records.
  + … Currently you can only create records using a coercion and that means you have to declare a variable to coerce the type.
  + … Having ~cast of~ would make it possible to do it in one step.
  + … Also it allows a stronger coercion (dropping fields, castings integers to decimals, etc.)
+ MK: The reason for doing sequences, arrays, and maps, is that records can contain them.
+ MK: All the changes are in the grammar, which isn’t ideal, but that’s the way it is.

MK describes the changes to the grammar, starting at ~CastExpr~.

+ MK: Casting an array just casts all the individual items.
+ MK: Casting a map involves casting all the entries. That’s slightly more complicated because it can cause duplicates to appear.
+ MK: Casting to a record type again casts every entry in the record type.
+ MK: Casting sequences is distributed through the earlier sections.
+ JWL: I think there may need to be some description here about the distinction between Schema lists and sequences.
+ MK: Yes, this is the only place we mix schema types and item types and it’s a little awkward.
+ JWL: I think you need to say something about casting that specialized form.
+ MK: I tried to do that, but I could say more. 
+ CG: I hadn’t looked at the latest version; do you remember what has changed in
  the last few days wrt the problem of record constructors may be nested or
  cannot be cast with the old rules.
+ MK: I don’t think I need to do anything to catch up with the fact that records have changed a bit.
  + … Except possibly the rule that when you cast a map to a record type, if an
    entry isn’t present you get an empty value and an error if that’s not
    allowed.
  + … If the target of the cast includes functions, you can use them unchanged
    if they are of the right type, otherwise you always get a type error.
+ CG: What about record field initializers?
+ MK: They aren’t there yet. That’s a separate PR. I thin when they exist, that will effect the coercion rules.
+ AP: This will require an awful lot of test cases!
+ CG: I think there are some typos.

Proposal: Accept this PR.

Accepted.

** PR #2788: 2774 Reversion of PR 2747 which allowed `A/B?C`
:PROPERTIES:
:CUSTOM_ID: pr-2788
:ID:       FBC7D984-6D3B-43A0-8B1F-3DA032327C42
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2788][#2788]]

+ MK: CG introduced a PR that allowed ~?C~ to appear as part of a step. But the
  precedence seemed to be wrong when we looked at the grammar.
  + … Couldn’t find a way of solving that, so this proposes rolling back the change.
+ CG: MK is completely right.

Proposal: Accept this PR.

Accepted.

** PR #2789: 2787 XQuery changes to merge declare record and declare type
:PROPERTIES:
:CUSTOM_ID: pr-2789
:ID:       B4723441-EC2C-4E5A-B09E-7A184A3BD98F
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2789][#2789]]

+ MK: The thinking was that there was less and less useful distinction between the two forms.
  + … This is just the XQuery part; I’d expect to do the XSLT part later.
+ MK: In the course of this, I also introduced initializers. I felt this needed constraints.
  + … The initializer can only be a function or a constant. To achieve that, I
    added ~()~ to the grammar production ~Constant~.

MK reviews the productions for a ~TypedRecordType~.

+ MK: If the initializer is a function, it must be inline and must have an empty closure.
+ MK: We have to distinguish named record types rather than unnamed ones.
+ MK: The coercion rules for maps to a record type now treat methods specially. The default value takes precedence, basically.
  + … The methods are as defined in the type; you can’t change the ~area~ function when you build a new record type.
  + … Or at least it’s more difficult, you have to use assignment or something.
+ MK: The section on recursive record types is rewritten, but it isn’t intended to be a substantive change.
+ MK: A new section is added about methods in records; largely explanatory.
+ MK: And named record types, as such, disappear.
+ CG: I’ve already commented on the PR. My concern is that we’d lose some features that we introduced a while ago.
  + … The ~declare record~ would be dropped, the initializer function would be
    optional, and we would lose simple initializers.
+ MK: Losing ~declare record~ is just syntax in principle, you should be able to do everything with ~declare type~
  + … I think there’s potentially a bit of a problem if you allow arbitrary
    initial values. It means what appears to be the same type can be a different
    type, depending on when the initial value expression is evaluated. And what
    if it has dependencies on types? That introduces an order of evaluation problem.
+ MK: I might have been over-restrictive, but I think some restrictions are necessary.

Some discussion of how substantive the change to remove ~declare record~ is.

+ CG: A restricted ~declare type~ and a full ~declare record~ declaration for
  other types might be useful.
+ MK: Yes. One reason for ~declare type~ is just for semantics.
+ MK: It’s a good point about initializers.

MK suggests we review this and come back to it.

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:ID:       2C2B0B10-53A9-4B82-ACE4-DD80B6DFC2E5
:END:

None heard.

