:PROPERTIES:
:ID:       A33BB91D-CADA-41EC-AA03-B41C44CCF7AB
:END:
#+title: QT4 CG Meeting 175 Minutes 2026-08-11
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

[[../][Meeting index]] / [[https://qt4cg.org][QT4CG.org]] / [[https://qt4cg.org/dashboard][Dashboard]] / [[https://github.com/qt4cg/qtspecs/issues][GH Issues]] / [[https://github.com/qt4cg/qtspecs/pulls][GH Pull Requests]]

#+TOC: headlines 6

* Summary of new and continuing actions [0/7]
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: new-actions
:ID:       E163C5FF-35A6-42C7-97C1-26018A7A55D1
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-167-03: NW to make a PR for #2482, fallback on bin:decode-string
+ [ ] QT4CG-167-05: MK to write a proposal to change #2393 so the functions return JNodes
+ [ ] QT4CG-167-07: NW to review tests for interpolated strings with edge cases in mind
+ [ ] QT4CG-167-09: NW to close all “nice to have” issues at the end of October if they haven’t progressed
+ [ ] QT4CG-170-01: RD to draft a proposal that attempts to address the lexical issues differently.
+ [ ] QT4CG-174-01: MK to make an issue or otherwise address CG’s comments on #2734.

* Draft Minutes
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: minutes
:ID:       0BDB88A2-D60E-4433-989D-7C30746646D1
:END:

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:ID:       F0ED304A-B587-4287-BF0F-CDE26E92E3BE
:END:

** Roll call [7/11]
:PROPERTIES:
:CUSTOM_ID: roll-call
:ID:       7815DDD1-075E-4C88-9A31-FD67706BCBC0
:END:

MK, JK give regrets.

+ [X] David J Birnbaum (DB)
+ [ ] Reece Dunn (RD)
+ [X] Christian Grün (CG)
+ [ ] Joel Kalvesmaki (JK)
+ [ ] Michael Kay (MK)
+ [X] Juri Leino (JLO)
+ [X] John Lumley (JWL)
+ [X] Alan Painter (AP)
+ [X] Wendell Piez (WP)
+ [ ] Bethan Tovey-Walsh (BTW)
+ [X] Norm Tovey-Walsh (NW) /Scribe/. /Chair/.

** Accept the agenda
:PROPERTIES:
:CUSTOM_ID: agenda
:ID:       9E01AE79-8B33-4350-A30B-0434746BB39C
:END:

Proposal: Accept [[../../agenda/2026/08-11.html][the agenda]].

Accepted.

** Approve minutes of the previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:ID:       3C647E5A-D1C7-4827-B402-82AF780C4C27
:END:

Proposal: Accept [[../../minutes/2026/07-28.html][the minutes of the previous meeting]].

Accepted.

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:ID:       8AB5EF3E-FFE6-4BE5-9EC6-FB0C5D9FFFB1
:END:

The next meeting is planned for 18 August.

JLO gives regrets.

** Review of open action items [0/6]
:PROPERTIES:
:CUSTOM_ID: open-actions
:ID:       AD7E58EB-760F-427C-93D2-A6F2ADF2D7AA
:END:

The action item list in the agenda was incorrect.

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-167-03: NW to make a PR for #2482, fallback on bin:decode-string
+ [ ] QT4CG-167-05: MK to write a proposal to change #2393 so the functions return JNodes
+ [ ] QT4CG-167-07: NW to review tests for interpolated strings with edge cases in mind
+ [ ] QT4CG-167-09: NW to close all “nice to have” issues at the end of October if they haven’t progressed
+ [ ] QT4CG-170-01: RD to draft a proposal that attempts to address the lexical issues differently.
+ [ ] QT4CG-174-01: MK to make an issue or otherwise address CG’s comments on #2734.

** Review of open pull requests and issues
:PROPERTIES:
:CUSTOM_ID: open-pull-requests
:ID:       ABCFD208-AA81-47C4-8BB1-2F8BB455DF95
:END:

This section summarizes all of the issues and pull requests that need to be
resolved before we can finish. See [[#technical-agenda][Technical Agenda]] below for the focus of this
meeting.

*** Merge without discussion
:PROPERTIES:
:CUSTOM_ID: merge-without-discussion
:ID:       33D68A8F-D3E1-403B-861B-36C24BB5759E
:END:

The following PRs are editorial, small, or otherwise appeared to be
uncontroversial when the agenda was prepared. The chairs propose that
these can be merged without discussion. If you think discussion is
necessary, please say so.

+ PR [[https://qt4cg.org/dashboard/#pr-2817][#2817]]: 2816 Advice for representing whitespace serialization params

Proposal: Accept without discussion.

Accepted.

* Technical agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:ID:       FCAA3383-47C5-401D-861D-DD8DA4FB532B
:END:

Diffs aren’t building at the moment, so I’m once again putting older issues
first and in MK’s absence, attempting to avoid his PRs.

** PR #2707: 1962 fn:map-to-element
:PROPERTIES:
:CUSTOM_ID: pr-2707
:ID:       21A0D820-3913-4E72-9A54-5BF90D1F01EB
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2707][#2707]].

CG introduces the PR.

+ CG: You know about ~fn:element-to-map~ that aids in the construction of maps and arrays to serialize as JSON.
  + … But there’s no way back, so I’m trying to write a function that does the inverse.
+ CG: Some information is lost, like comments, processing instructions, whitespace, text nodes…
  + … That can’t be reconstructed, but in principle everything that’s created by the function can be converted back.
+ CG: This function tries to provide a way back, but it doesn’t promise to convert arbitrary maps to elements.
+ CG: The conversion of lists fails without a plan.
+ CG: I tried to reject any input that can’t be converted back.
+ CG: There are lots of rules…
+ CG: All the options on ~fn:element-to-map~ are supported here too.

+ NW: It’s not for general conversions, but we can’t tell that a map came from
  ~fn:element-to-map~. Does that just mean you’ll fail if you encounter
  something unexpected?
+ CG: Yes.
+ JWL: Suppose I have a map in my structure that I’ve made myself and parts of
  it are node trees, would that be permitted? I can see a good case for supporting that.
  + … What I want to do is get something out that isn’t a map, but I want as much information as I can get.
+ CG: I think the tricky part is how to decide when it’s expected what you want to create and when it’s an error.
  + … I decided to reject as much as possible, but maybe we should allow more things.
  + … We could have a liberal or strict mode; I’ve got a proposal to do that for ~fn:element-to-map~.
+ JWL: Can you show me the second example, the one with dates. What does “dates” mean in the plan?
+ CG: It’s just a placeholder. I’ll think about that some more.
+ WP: This is awesome. A *lot* of money has been spent on this kind of
  conversion problem. What is the relationsip between the plans and record
  types? Record types are a phenominal way to nail down the structure.
  + … We need to know how to go the other way and we also need to be able to
    publish plans for specific record types.
  + … I’d like to see this extended, even if it doesn’t have a complete mapping the other way, it’s going to be game changing.
+ JLO: I’m also excited to see this. In the introduction, why doesn’t ~E =>
  element-to-map(OPTS) => map-to-elements()~ end with ~=> E~. That would make it clearer to me.
+ NW: But you don’t gets comments and processing instructions and such.
+ AP: Could we call it ~E’~?

Some discussion of deep-equal and the detection of comments and processing instructions.

+ JLO: That’s mixed content in an array. Is there way to define that as really a text node, or is that impossible?
+ CG: Basically, the rules are just inverted here. We could extend the existing
  rules for element map to make it easier to convert it back.
+ WP: The data might start in JSON, and moving into XML might be a way to clean it.
+ JLO: I have seen this @ notation and # content notation a lot. Is there a name for that?
+ CG: It would have to be defined in the first part.

Proposal: merge this PR?

Accepted.

** PR #2789: 2787 XQuery changes to merge declare record and declare type
:PROPERTIES:
:CUSTOM_ID: pr-2789
:ID:       DE70B089-D13A-4E4F-8685-B3DA0FDBEA28
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2789][#2789]].

Skip. This one is MK’s.

** PR #2793: 2729 fn:replace: named groups (+other regex functions)
:PROPERTIES:
:CUSTOM_ID: pr-2793
:ID:       4CEAFE06-247F-457D-A067-2BB62BF2ABC1
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2793][#2793]].

+ CG: This was already reviewed by MK. What we did last time was add named groups.
  + … And ~fn:replace~ also allows you to define named groups. I’ve added references for them in this PR.
+ CG: The syntax is similar to other languages, ~\k<name>~. And I added some examples.
+ NW: Are those embedded angle brackets going to be a problem?
+ CG: Not in XPath and XQuery, I don’t know about XSLT.
+ NW: Yeah, that’s giving me a little bit of heartburn.
+ CG: In ~fn:replace~ we’ve extended the type of the replacement text to be more flexible.

CG reviews some of the new examples.

+ CG: In ~fn:analyze-string~ we make a few extensions as well. The name becomes
  part of the returned group element.

+ JLO: Would it make sense to implement this in a way that if you don’t have
  named groups, you return an array not a map?
+ CG: I think it’s problematic to have too many different return types. Patterns
  can also be dynamic, so static typing is much harder.
+ WP: Maybe a default name to handle those cases? Naming them “1”, “2”, and “3” might be even more confusing.
+ CG: If there aren’t names, we get positions.

Proposal: merge this PR?

Accepted.

** PR #2794: 2748 CSV Serialization
:PROPERTIES:
:CUSTOM_ID: pr-2794
:ID:       C852950C-6F14-48AD-A196-B78DD73BC9BC
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2794][#2794]].

+ CG: Many different specs are involved, but most of them are only tables or schema stuff. The interesting part is in serialization.
  + … I’ve added a new output method for CSV.
+ CG: The options for CSV are handled like the JSON options, they only apply to the CSV output method.

CG reviews the description of the method.

+ CG: Other options, like the BOM, also apply.

+ JWL: How many of the options are in common with the ~fn:parse-csv~ function?
  + … Should there be a common record structure?
+ CG: Many of them are the same.
+ CG: We tried to have one record type and be able to round trip the data with the same options.
+ CG: But the keys need to be named differently because we don’t have the ~csv-~ prefix for the parsing maps.
+ JWL: So it’s actually a grid, there’s common stuff in the CSV space, but you
  also have the other ones coming from other parts of serialization.
  + … Then we decided that records aren’t extensible, so I can’t combine two records to make a big record!
+ JWL: I guess you could say in the spec, that “this record” is the combination of “these other two records”.
  + … But you can’t programmatically do it.
+ CG: In BaseX, we allow option parameters to be a map.
+ JLO: This is an interesting addition; we have the same problems as JSON so
  maybe we’ll have more need to have the options structured by data format.

Proposal: merge this PR?

Accepted.

** PR #2795: 2338 Nomenclature: node(), gnode(), xnode()
:PROPERTIES:
:CUSTOM_ID: pr-2795
:ID:       08B036ED-817D-4033-94EE-A99DA052EC9E
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2795][#2795]].

+ CG: We have general nodes, GNodes, that came into life because of JNodes, but that may not be clear to many users.
  + … The idea was to drop this term again and rename existing nodes() to xnodes() and to have node() mean either.
+ CG: I haven’t dropped the use of ~GNodes~ in the spec; that still makes sense.
  It’s not really possible to use ~GNode~ for the GNode type in all cases.
  + … But the user won’t notice this anymore.
+ CG: But maybe we should see what MK thinks explicitly.
+ JWL: It’s backwards compatible with existing code and such. But will there be
  a sense that people have to change ~node()~ to ~xnode()~ in all their XPath expressions?
  + The spec has changed in this regard. Now that you’ve got the possibility of
    JNodes, do I have to go through and change it all?
+ CG: I think it won’t be so much of a problem. It’s backward compatible. Most
  of the functionality works with both kinds of nodes.
  + … This will reduce the number of places where error messages, for example,
    contain ~xnode()~ which can be confusing.
+ AP: Is it interesting to try to do some exercises to look for backwards incompatibility?
  + … I think it’s been helpful to know that “node” still means “XML node” and I need to say “gnode” if I want both kinds.
  + … Is there a more general problem that we’re reversing the original position?
+ CG: There are some remarks that try to point out the differences. Perhaps I should highlight those changes.
+ AP: Maybe we just need to be very closely.
+ WP: I think a close review is in order. I think this is actually a good idea,
  even a silver lining. This brings the JSON people into parity, you don’t need to rearrange the names.
  + … The concerns that have been raised can be addressed. We can gloss over the
    meaning of “GNode” in the prose. These are all features as much as they are problems.
+ JLO: I find this change bold but also necessary. 
  + … Anything is a node for me, the term “gnode” doesn’t roll off the tongue.

Let’s come back to this in a week.

** PR #2812: 2811 fn:decode-from-uri: to +, or not to +
:PROPERTIES:
:CUSTOM_ID: pr-2812
:ID:       0881BFE5-F8A2-4E90-BD7F-F228BD95C39A
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2812][#2812]].

+ CG: The change is minor. It replaces a “+” with a “ ”.
  + … The use of “+” is a HTML form rule, not a URI rule.
+ CG: There’s also an example in ~parse-uri~ where the conversion is incorrect.

Proposal: merge this PR?

Accepted.

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:ID:       03098EF3-3306-4658-93A5-BC560FC25E1C
:END:

None heard.
