:PROPERTIES:
:ID:       1BC8DDC8-56A3-4139-8E48-FC04DCC473F2
:END:
#+title: QT4 CG Meeting 181 Minutes 2026-09-22
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

[[../][Meeting index]] / [[https://qt4cg.org][QT4CG.org]] / [[https://qt4cg.org/dashboard][Dashboard]] / [[https://github.com/qt4cg/qtspecs/issues][GH Issues]] / [[https://github.com/qt4cg/qtspecs/pulls][GH Pull Requests]]

#+TOC: headlines 6

* Summary of new and continuing actions [0/7]
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: new-actions
:ID:       DE996CD5-C0DE-4E1F-A235-768D96E72CB7
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-167-07: NW to review tests for interpolated strings with edge cases in mind
+ [ ] QT4CG-167-09: NW to close all “nice to have” issues at the end of October if they haven’t progressed
+ [ ] QT4CG-170-01: RD to draft a proposal that attempts to address the lexical issues differently.
+ [ ] QT4CG-177-01: NW to put the progress graphs back in the minutes.
+ [ ] QT4CG-181-01: CG to open an issue about a possibly better name for “the url base64url” function

* Draft Minutes
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: minutes
:ID:       93F3E81B-C8AE-46A1-8310-173081D072A1
:END:

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:ID:       BB4C31F5-4332-4C1E-92CB-CC6F9F4785B9
:END:

** Roll call [10/11]
:PROPERTIES:
:CUSTOM_ID: roll-call
:ID:       55331BC6-F11C-4F96-8800-BA082F0ABB11
:END:

+ [X] David J Birnbaum (DB)
+ [X] Reece Dunn (RD)
+ [X] Christian Grün (CG)
+ [X] Joel Kalvesmaki (JK) [:07-]
+ [X] Michael Kay (MK)
+ [ ] Juri Leino (JLO)
+ [X] John Lumley (JWL)
+ [X] Alan Painter (AP)
+ [X] Ruvim Pinka (RP)
+ [X] Wendell Piez (WP)
+ [X] Norm Tovey-Walsh (NW) /Scribe/. /Chair/.


** Accept the agenda
:PROPERTIES:
:CUSTOM_ID: agenda
:ID:       8EAFDBD9-DEDF-439D-A9BA-8A390D165F4B
:END:

Proposal: Accept [[../../agenda/2026/09-22.html][the agenda]].

Accepted.

** Approve minutes of the previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:ID:       4780A7C0-B4D7-4128-AA5B-B57377A39F43
:END:

Proposal: Accept [[../../minutes/2026/09-15.html][the minutes of the previous meeting]].

Accepted.

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:ID:       697CBCB8-0BDA-45F4-8658-B29300C93492
:END:

The next meeting is planned for 29 September.

AP gives regrets.

** Review of open action items [1/6]
:PROPERTIES:
:CUSTOM_ID: open-actions
:ID:       0292F828-2690-4955-8F03-92A0CA2235C7
:END:

+ [ ] QT4CG-143-02: MK to try to recover the ability to extract formal equivalences into tests
+ [ ] QT4CG-167-07: NW to review tests for interpolated strings with edge cases in mind
+ [ ] QT4CG-167-09: NW to close all “nice to have” issues at the end of October if they haven’t progressed
+ [ ] QT4CG-170-01: RD to draft a proposal that attempts to address the lexical issues differently.
+ [ ] QT4CG-177-01: NW to put the progress graphs back in the minutes.
+ [X] QT4CG-179-01: CG to fix the typo “or absent” in 14.6.5.

** Review of open pull requests and issues
:PROPERTIES:
:CUSTOM_ID: open-pull-requests
:ID:       C2BD9280-1922-4AE4-A528-3EE3F5CBC10A
:END:

This section summarizes all of the issues and pull requests that need to be
resolved before we can finish. See [[#technical-agenda][Technical Agenda]] below for the focus of this
meeting.

*** Close without action
:PROPERTIES:
:CUSTOM_ID: close-without-action
:ID:       A0CC7E0A-D665-40A3-8964-1E602D8E01BD
:END:

It has been proposed that the following issues be closed without action.
If you think discussion is necessary, please say so.

+ Issue [[https://github.com/qt4cg/qtspecs/issues/2785][#2785]]: Make XSLT tunnel parameters available dynamically as a map

Propposal: close without action.

Accepted.

*** Substantive PRs
:PROPERTIES:
:CUSTOM_ID: substantive
:ID:       052184A4-4730-419C-8F3F-21F3B3317AC4
:END:

The following substantive PRs were open when this agenda was prepared.

+ PR [[https://qt4cg.org/dashboard/#pr-2862][#2862]]: 2861 Clarify CSV serialization edge cases
+ PR [[https://qt4cg.org/dashboard/#pr-2878][#2878]]: 2073 JNodes and Sequences
+ PR [[https://qt4cg.org/dashboard/#pr-2881][#2881]]: 2873 fn:update: another attempt
+ PR [[https://qt4cg.org/dashboard/#pr-2885][#2885]]: 2849 xs:integer vs. restricted subtypes
+ PR [[https://qt4cg.org/dashboard/#pr-2910][#2910]]: 2909 Binary functions: Base64 URL en-/decoding
+ PR [[https://qt4cg.org/dashboard/#pr-2911][#2911]]: 2693 Drop type patterns (and other revisions)
+ PR [[https://qt4cg.org/dashboard/#pr-2912][#2912]]: 1777 Revise XSLT shallow copy for JNodes
+ PR [[https://qt4cg.org/dashboard/#pr-2916][#2916]]: 2915 `fn:current`: inline functions and `fn:function-lookup`
+ PR [[https://qt4cg.org/dashboard/#pr-2918][#2918]]: 2600 Options on fn:collection()
+ PR [[https://qt4cg.org/dashboard/#pr-2920][#2920]]: 2813 clarifications for xsl:result-document

* Technical agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:ID:       157FF17D-9748-4E32-A504-4D62C5BEB4E4
:END:

** PR #2862: 2861 Clarify CSV serialization edge cases
:PROPERTIES:
:CUSTOM_ID: pr-2862
:ID:       12B54B01-0CA6-4E00-A4AB-A8CA22506BF4
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2862][#2862]]

We ended last week on this one. MK walks through the PR.

The new line character is an implementation-defined string.

Proposal: accept this PR.

Accepted.

** PR #2878: 2073 JNodes and Sequences
:PROPERTIES:
:CUSTOM_ID: pr-2878
:ID:       A3F36002-557A-4D78-94E2-47CB0387C856
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2878][#2878]]

+ MK: Shallow-copy needs to have a clear model of how JNodes and sequences are processed.
  + … A shallow-copy mode should return the input unchanged if there are no other rules.
  + … That means we have to be clear about how everything is modeled in terms of JNodes.
+ MK: There’s work on the data model, then most is in XPath/XQuery.

MK reviews the changes to the data model.

+ MK: JPosition is dropped.
  + … There are four kinds of JNodes: a singleton array, a singleton map, a sequence, or a leaf JNode wrapping a singleton.
  + … I’ve adopted the notation ~<jnode>~ for describing the JNode trees:

#+begin_src xml
<jnode kind='map' key='()' value='{ "a": 11, "b": [22, 33], "c": ()}'>
  <jnode kind='leaf' key='a' value='11'/> 
  <jnode kind='array' key='b' value='[22, 33]'>
    <jnode kind='leaf' key='1' value='22'/>
    <jnode kind='leaf' key='2' value='33'/>
  </jnode>
  <jnode kind='leaf' key='c' value='()'/>
</jnode>
#+end_src 


+ MK: That one is easy because it doesn’t have any sequences. Consider this one:

#+begin_src xml
<jnode kind='map' key='()' value='{ "a": 11, "b": [22, 33], "c": (44, 55)}'>
  <jnode kind='leaf' key='a' value='11'/> 
  <jnode kind='array' key='b' value='[22, 33]'>
    <jnode kind='leaf' key='1' value='22'/>
    <jnode kind='leaf' key='2' value='33'/>
  </jnode>
  <jnode kind='sequence' key='c' value='(44, 55)'>
    <jnode kind='leaf' key='1' value='44'/>
    <jnode kind='leaf' key='2' value='55'/>
  </jnode>
</jnode>
#+end_src

+ MK: Now the structure of the item differs for singletons or sequences.
+ MK: I propose we invent a new axis. The idea is that it normalizes the
  representation so you don’t have to cope with the fact that they’re different.
+ MK: There’s a bit of further detail about the properties of JNodes.

MK reviews the changes in XPath.

+ MK: There’s a new axis called the ~item~ axis. It’s there so you can find the items in a sequence.

MK reviews the description of the ~item~ axis which applies only to JNodes.

+ MK: The /Selectors for JNodes/ section has been updated to use the new terminology.

MK reviews the examples in 4.7.5.4.

+ RD: I’ve got two questions. Given that we’ ve dropped JPosition, that means
  that position is now implicit in the XML representation. 
+ MK: Yes. In fact, it’s in the key property.
+ RD: In the array case, the key is the position.
+ MK: Yes.
+ RD: Is the ~item~ axis usable for a sequence? If you’ve got a sequence of XML elements, could you use the item axis?
+ MK: No, it’s defined only on JNodes.
+ RD: You could use a filter expression…with filter expressions you can access
  items in the sequence by position. Would that work the same with JNode
  sequences?
+ MK: Yes. The only thing the ~item~ axis does is it gives you the flattening
  that singleton sequences and longer sequences have homogeneous behavior.
  + … For the vast majority of cases it isn’t needed. It’s not needed for JSON
    because there aren’t sequences. And it’s not needed in recursive descent.
+ WP: For clarification, this is because we have sequences on values in JNodes and we have to deal with them.
+ MK: Yes, that’s right.
+ WP: And that’s in our world, not in JSON.
+ MK: Yes.
+ WP: What was the motivation for an axis rather than something else?
+ MK: It’s the best solution I could come up with. I considered making it a property of the child axis, but …
+ WP: I guess the uneasiness is what happens when you use it elsewhere.
+ MK: Well, it’s defined on JNodes, so in any other case, like the other axes,
  it’ll give you an empty sequence.
+ WP: My general sense is that this is nice and fits, but it’s going to be somewhat hard to explain.
  + … In particular, do we ever use this axis with a name?
+ MK: I haven’t come across a case where you’d do that. But the situation I
  haven’t really explored yet is where you have a structure where a map can
  contain either a single map or a sequence of maps.
  + … But I don’t think anyone is going to do that. An array of maps is just easier.

Some discussion of using a function; it could be done, but it doesn’t fit into path expressions as nicely.

+ JWL: If you use the ~item~ axis on something that isn’t a JNode, you’d get an
  empty sequence back. Do you anticipate something similar to the static
  analysis about using attributes on a text node for example.
+ MK: I hadn’t worked out that detail.
+ RD: If you can be sure that a value will never be a JNode, then it should be possible to emit a warning.
+ MK: The only case where you get an error is if you apply it to an XNode. Like
  using the attribute axis on a JNode.
  + … It’s well defined in all cases because everything is a sequence.
+ WP: And it combines the semantics of a couple of axis.
+ MK: Yes, it’s roughly like the child axis on a sequence and the self axis for a singletone.

Proposal: accept this PR.

Accepted.

** PR #2912: 1777 Revise XSLT shallow copy for JNodes
:PROPERTIES:
:CUSTOM_ID: pr-2912
:ID:       373383FC-CF0D-4EBB-A295-158694947886
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2912][#2912]]

MK proposes this one next because it’s closely related to the previous.

+ MK: It drops ~shallow-copy-all~ mode which we introduced in an attempt at
  backwards compatibility that’s no longer needed.
  + … There are two parts, the shallow copy mode and the ~xsl:copy~ instruction itself.
+ MK: I do define what happens with JNodes in the other processing modes, but
  it’s not significant.
+ MK: The shallow-copy semantics can be expressed in a single template, modified
  to avoid errors.
+ MK: There are some new examples.
+ MK: The examples are repeated for the JTree.
+ MK: One usability thing I discovered was “how do you start off the process?”
  + … With an XTree, you get an implicit document node. You don’t get that implicit behavior with a JTree.
  + … There are examples of deleting and renaming JNodes.
+ MK: I’ve done a lot of work to think through the detail, but we won’t really know until we’ve implemented it.
  + … I think the mechanics are reasonably sound.
+ MK: The other part is the shallow ~xsl:copy~ instruction itself.
+ MK: The text has been broken into sections for clarity.
  + … The rules for XNodes have been refactored, but the semantics are the same.
  + … The section on JNodes is new.
+ JWL: In the example where you’re renaming in the JTree.
  + … What does ~.*~ mean?
+ MK: It’s a sequence pattern “.” that matches any item followed by “*” sequence occurrence indicator.
+ JWL: Okay. That makes sense, but it looks odd.
+ RD: I don’t see that defined in the grammar.
+ MK: This is a JNode pattern defined in the XSLT specification.
+ JK: I’m happy to see ~shallow-copy-all~ disappear. It never sat well with me. You said this was closely related to the previous PR.
  You introduced the ~item~ axis, how do they work in templates?
+ MK: For this recursive descent pattern, we don’t need it. It purely uses the ~child~ axis which does the right thing.
+ JK: It might be worth a note somewhere about that.
+ MK: We don’t need it for this design pattern, but we might in other cases.

Proposal: accept this PR.

Accepted.

** PR #2910: 2909 Binary functions: Base64 URL en-/decoding
:PROPERTIES:
:CUSTOM_ID: pr-2910
:ID:       44C046BB-E1EE-477B-B84D-27BB2D18BC61
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2910][#2910]]

CG introduces the PR.

+ CG: How many features do we want to add? I tend to create new issues and PRs
  when things are simple and straightforward.
  + … This is something that came up in a use case.
  + … I thought two convenience functions would be helpful.

CG reviews the semantics.

+ CG: I thought the binary module was a good place to put them.
+ RD: This is for base64 data in a URL parameter instead of a URL. Would a
  slightly different name be better?
  + … This seems to indicate that the entire URL is base64 encoded.
  + … Maybe url-encode/url-decode-base64
  + … url-encode is a common name for encoding query parameters and the like.
+ CG: We could add component.

Some discussion of the possibilities.

+ MK: Where is this defined?
+ CG: RFC 4648
  + … I’ve seen it outside URLs too.

Proposal: accept this PR.

Accepted.

ACTION QT4CG-181-01: CG to open an issue about a possibly better name for “the url base64url” function

** PR #2916: 2915 `fn:current`: inline functions and `fn:function-lookup`
:PROPERTIES:
:CUSTOM_ID: pr-2916
:ID:       FC293191-8B0B-4071-A33E-0B83102575E7
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2916][#2916]]

Skip for now, the PR didn’t build.

** PR #2881: 2873 fn:update: another attempt
:PROPERTIES:
:CUSTOM_ID: pr-2881
:ID:       D87A9012-E108-41C6-B851-DAD8761B1335
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2881][#2881]]

+ CG: I’ve revised the prose.
+ CG: I tried to make the rules more explicit, separating XNodes and JNodes.
  + … And I’ve added some examples.
+ CG: If we want a single function, I think this is a good compromise.
  + … Mostly what turned out difficult was defining different functions that do more specific things.
  + … Delete is easy, but update and replace are already complicated.
  + … I think one function to do everything is a good way forward, but we could add more.
+ JK: I thought update was an XQuery thing but not an XPath thing.
  + … We’re introducing update to XPath?
+ CG: Yes, there’s an XQuery update feature, but the idea here is to have
  something that works for both JNodes and XNodes.
+ MK: This doesn’t have the conceptual problems of XQuery update: it doesn’t
  introduced pending update lists or anything like that.
  + … It’s a single function that returns an updated tree.

General consensus that this is a big change.

+ CG: There have been some iterations. MK proposed one before; there have been other attempts.
  + … I ended up with this attempt.
+ MK: I’d like to do a detailed review before signing off on it. I haven’t had a chance to do that.
+ WP: This is the opposite of XProc; this is like having a mini transformation on the front end. It’s almost like pipelining in XSLT.
  + … I’m curious to see where it goes, but I don’t think it’s as important for XSLT.
+ MK: In the context of JTrees, it’s significant because we don’t have node identity in JTrees.
  + … We can modify a tree but only change small parts. You can have a
    functional update that creates a new 100mb data structure while only
    changing three bytes.
  + … That’s much harder to achieve with an XTree because of the node identity problem.
  + … The shallow-copy is probably going to be linear in the size of the tree.
+ RD: In the past, I’ve had some XSLTs that have 4 to 6 different phases. I
  wonder if this update function could simplify some of that?
+ JK: It looks like in all of the examples the second argument is always a pattern.
+ CG: It’s always a function because the input needs to be copied. The function
  is evaluated on a copy of the node. That’s why you can’t directly specify the
  path.
+ MK: If you supply that pattern as a predicate, then the problem is that you’re
  going to have to search the whole tree to find matches. A function that
  selects them is probably going to be more efficient.
  + … Doing small updates to large trees with a pattern that you have to test against a lot of nodes in the tree isn’t ideal.

Ran out of time.

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:ID:       3FC7AF30-7637-4EA0-8CBB-FECD7EF47A65
:END:

None heard.
