:PROPERTIES:
:ID:       75FE8166-82EA-446F-8D80-4A1F2A1C177C
:end:
#+title: QT4 CG Meeting 132 Minutes 2025-08-12
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

[[../][Meeting index]] / [[https://qt4cg.org][QT4CG.org]] / [[https://qt4cg.org/dashboard][Dashboard]] / [[https://github.com/qt4cg/qtspecs/issues][GH Issues]] / [[https://github.com/qt4cg/qtspecs/pulls][GH Pull Requests]]

#+TOC: headlines 6

* Minutes
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: minutes
:END:

Approved [[../2025/08-19.html][at meeting 133]] on 19 August 2025.

* Summary of new and continuing actions [0/11]
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: new-actions
:END:

+ [ ] QT4CG-116-01: Add a specific error code for unsupported options on doc and doc-available
+ [ ] QT4CG-118-01: MK to make an incorrect type raise an error in #1906
+ [ ] QT4CG-127-01: NW to diagram the JTree representing arbitrary XDM content.
+ [ ] QT4CG-128-03: NW to compare the file: module against the equivalent XProc 3.1 steps
+ [ ] QT4CG-131-01: MK to add a non-schema aware result.
+ [ ] QT4CG-131-02: MK to expand on the ~$E := <e A="p q r"…~ example
+ [ ] QT4CG-131-03: MK to change “invert” to “transpose” in the matrix example.
+ [ ] QT4CG-132-01: MK to add more examples for ~innermost~, ~outermost~, ~has-children~ and ~path~ with JNodes
+ [ ] QT4CG-132-02: MK to double-check the signature of ~innermost~
+ [ ] QT4CG-132-03: MK to double-check stray text in h.i. in ~path~
+ [ ] QT4CG-132-04: MK to add resize to the rectangle in the example of chaining method calls and flesh out the example.

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:END:

** Roll call [8/11]
:PROPERTIES:
:CUSTOM_ID: roll-call
:END:

Regrets: BTW.

+ [X] David J Birnbaum (DB)
+ [X] Reece Dunn (RD)
+ [X] Christian Grün (CG)
+ [X] Joel Kalvesmaki (JK) [:15-]
+ [X] Michael Kay (MK)
+ [ ] Juri Leino (JLO)
+ [X] John Lumley (JWL)
+ [X] Wendell Piez (WP)
+ [ ] Ed Porter (EP)
+ [ ] Bethan Tovey-Walsh (BTW)
+ [X] Norm Tovey-Walsh (NW) /Scribe/. /Chair/.

** Accept the agenda
:PROPERTIES:
:CUSTOM_ID: agenda
:END:

Proposal: Accept [[../../agenda/2025/08-12.html][the agenda]].

Accepted.

** Approve minutes of the previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:END:

Proposal: Accept [[../../minutes/2025/07-29.html][the minutes of the previous meeting]]. 

Accepted.

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:END:

The following meeting is scheduled for 19 August 2025.

No regrets heard.

(The CG will take a short recess in late August. We will *not* meet on 26 August,
2 September, or 9 September.)

** Review of open action items [2/9]
:PROPERTIES:
:CUSTOM_ID: open-actions
:END:

(Items marked [X] are believed to have been closed via email before
this agenda was posted.)

+ [X] QT4CG-082-02: DN to work with NW to come to agreement on the fn:ranks proposal
  + Overtaken by events
+ [ ] QT4CG-116-01: Add a specific error code for unsupported options on doc and doc-available
+ [ ] QT4CG-118-01: MK to make an incorrect type raise an error in #1906
+ [ ] QT4CG-127-01: NW to diagram the JTree representing arbitrary XDM content.
+ [ ] QT4CG-128-03: NW to compare the file: module against the equivalent XProc 3.1 steps
+ [ ] QT4CG-131-01: MK to add a non-schema aware result.
+ [ ] QT4CG-131-02: MK to expand on the ~$E := <e A="p q r"…~ example
+ [ ] QT4CG-131-03: MK to change “invert” to “transpose” in the matrix example.
+ [X] QT4CG-131-04: JK to double check the use of ~&lt;&lt;~ in the grammar where ~&gt;&gt;~ might have been intended

** Review of open pull requests and issues
:PROPERTIES:
:CUSTOM_ID: open-pull-requests
:END:

This section summarizes all of the issues and pull requests that need to be
resolved before we can finish. See [[#technical-agenda][Technical Agenda]] below for the focus of this
meeting.

*** Blocked
:PROPERTIES:
:CUSTOM_ID: blocked
:END:

The following PRs are open but have merge conflicts or comments which
suggest they aren’t ready for action.

+ PR [[https://qt4cg.org/dashboard/#pr-2124][#2124]]: 573 Functions to Construct Trees
+ PR [[https://qt4cg.org/dashboard/#pr-2120][#2120]]: 2007 Revised design for xsl:array
+ PR [[https://qt4cg.org/dashboard/#pr-2019][#2019]]: 1776: XSLT template rules for maps and array

*** Merge without discussion
:PROPERTIES:
:CUSTOM_ID: merge-without-discussion
:END:

The following PRs are editorial, small, or otherwise appeared to be
uncontroversial when the agenda was prepared. The chairs propose that
these can be merged without discussion. If you think discussion is
necessary, please say so.

+ PR [[https://qt4cg.org/dashboard/#pr-2158][#2158]]: 2157 Editorial updates to F+O §5.5 (Unicode collations)
+ PR [[https://qt4cg.org/dashboard/#pr-2146][#2146]]: Require at least one character in StringTemplateFixedPart
+ PR [[https://qt4cg.org/dashboard/#pr-2145][#2145]]: Allow implicit whitespace in StringInterpolation
+ PR [[https://qt4cg.org/dashboard/#pr-2141][#2141]]: Remove nested paragraphs
+ PR [[https://qt4cg.org/dashboard/#pr-2137][#2137]]: 2136 Drop full-width < and > symbols
+ PR [[https://qt4cg.org/dashboard/#pr-2135][#2135]]: QT4CG-131-01/02 Expand on example as actioned

Proposal: merge these PRs without discussion.

*** Close without action
:PROPERTIES:
:CUSTOM_ID: close-without-action
:END:

It has been proposed that the following issues be closed without action.
If you think discussion is necessary, please say so.

+ Issue [[https://github.com/qt4cg/qtspecs/issues/1852][#1852]]: fn:values-except: Return atomic values that occur in A but not in B
  + MK proposes closing on a value judgement; didn’t meet the minimum bar for
    adding the function. But that’s a personal judgement.
  + JWL: Easy enough to write your own?
  + MK: Yes.
  + CG: Background: we had some users who were asking for the function. They noticed that
    there’s no equivalent predicate solution that’s fast enough. 
    + … If you have a dedicated function, it’s easier to optimize. But we have maps and
      there are no other comments, so I’m fine with closing it.
+ Issue [[https://github.com/qt4cg/qtspecs/issues/1698][#1698]]: Allow select attribute for xsl:call-template instruction
+ Issue [[https://github.com/qt4cg/qtspecs/issues/714][#714]]: Function annotations in XSLT
  + JWL: If you really want to do this you can pre-process the source code that contains a map.
  + MK: They wouldn’t be visible as annotations, but you can get the information.
  + JWL: You can do it yourself.
  + RD: That’s defining the equivalent of XQuery annotations on functions. Those are used in
    different places, like BaseX and other processors support REST XQ through annotations.
  + MK: There are two things here; being able to define annotations. You could
    do that with a vendor-defined extension attribute. The other is having the
    annotations available dynamically for interrogation. That’s subtle enough,
    we can leave users to design their own.
  + RD: I’ve used it in the past for roles.
  + MK: You can do that with extension attributes. It was a nice idea, but we can live without it.
  + RD: That means if you’re importing a function from XSLT, you can’t use the
    annotation mechanism in XQuery to interrogate the function.
  + WP: The more I hear, the more I’m with JWL. There are ways of doing this.
+ Issue [[https://github.com/qt4cg/qtspecs/issues/150][#150]]: fn:ranks: Produce all ranks in applying a function on the items of a sequence
  + PR [[https://qt4cg.org/dashboard/#pr-1062][#1062]]: 150bis revised proposal for fn:ranks

Proposal: close these issues and PRs without further action.

* Technical agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:END:

** PR #2116: 2112 Refine/revise the rules for get() in node tests
:PROPERTIES:
:CUSTOM_ID: pr-2116
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2116][#2116]]

Defer until later. (Maybe later today, maybe next week.)

** PR #2120: 2007 Revised design for xsl:array
:PROPERTIES:
:CUSTOM_ID: pr-2120
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2120][#2120]]

+ MK: Not ready for discussion. I need to rethink it.

** PR #2156: 2092 Drop map:pair, map:of-pairs, map-pairs
:PROPERTIES:
:CUSTOM_ID: pr-2156
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2156][#2156]]

+ MK: We have too many ways to do things; I like these functions, but they are
  one-liners with JNodes. So let’s simplify the spec by dropping them.
+ JWL: I wonder if it’s worthwhile putting them in as examples somewhere.
+ MK: We could have a rag-bag appendix of functions in F&O.
+ WP: That would be awesome.

Proposal: accept this PR.

Accepted.

** PR #2155: 2150 Define patterns for JNodes
:PROPERTIES:
:CUSTOM_ID: pr-2155
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2155][#2155]]

Defer until later.

** PR #2154: 2152 Revise rules for enumeration types
:PROPERTIES:
:CUSTOM_ID: pr-2154
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2154][#2154]]

MK introduces the PR. Only the XPath and XQuery specs are effected.

+ MK: The only material change for users is that ~instance of~ now does the
  required thing.
  + … We still define them as a union of singleton enumerations
  + … But a singleton is no longer defined as a type derived from restriction,
    that stops ~instance of~ working.
  + … This defines it as a new kind of subtype of string.
  + … The main reason to change this is so that you can use ~instance of~ tests
    in XSLT Patterns because patterns don’t use coercion.
+ JWL: Is there any use case where people might want to use other collations?
+ MK: Maybe, but the consequences would be horrible.

Proposal: accept this PR.

Accepted.

** PR #2149: 2100 Make innermost, outermost, has-children, path apply to JNodes
:PROPERTIES:
:CUSTOM_ID: pr-2149
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2149][#2149]]

MK introduces the PR.

+ MK: This generalizes a few more functions so that they work on JNodes.
  + … These could do with more examples. 

ACTION: QT4CG-132-01: MK to add more examples for ~innermost~, ~outermost~, ~has-children~ and ~path~ with JNodes
ACTION: QT4CG-132-02: MK to double-check the signature of ~innermost~

MK walks through the revised functions.

Some discussion of why ~has-children~ exists at all: streaming.

ACTION: QT4CG-132-03: MK to double-check stray text in h.i. in ~path~

Some discussion of where the “TODO” note is leading; will be resolved when we
sort out the question of JNodes and sequences.

Proposal: accept this PR.

Accepted.

MK will address the actions and then merge the PR.

** PR #2147: 2143 Redesign of method calls
:PROPERTIES:
:CUSTOM_ID: pr-2147
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2147][#2147]]

The design of methods was just too baroque; CG made a simplification proposal.
Rather than overloading the ~?~ operator, we have a separate operator for
invoking methods.

+ MK: We introduce a new operator ~?>~. We can debate how to spell it later.
  + … No magic semantics for ~?~ anymore. Instead there’s a new expression.
+ MK: You can’t use partial function application in this case. It’s a simplification.
+ CG: I think I like this solution. Mostly we had different proposals; the other
  syntax was a little shorter but it wasn’t as composable.
+ JWL: Given the example with chaining and resize; would it not be worthwhile
  putting the resize method into the example.

ACTION: QT4CG-132-04: MK to add resize to the rectangle in the example of chaining method calls and flesh out the example.

+ JK: One of the examples that confuses me is the rectangle example.
  + … Area is defined in rectangle as a 1 arity function but it looks like you’re invoking a 0 arity function.
  + … Can you use ~area(.)~?
+ MK: No, like the arrow syntax it implicitly passes the first argument.
+ JK: If someone were to jigger the function, what are the rules?
+ MK: No, the map has to be the first argument and it’s implicitly set.
+ JK: More examples would help. An example that invites external parameters would also be helpful.
+ RD: The only reserved names are things like ~function~ and ~switch~.
+ MK: I’m not sure even those are reserved; they’re fine in the context of the record.
+ JWL: Thinking about resize; it has to produce a new rectangle that has to have
  an area method and a resize method and that needs a real example.
+ RD: You could potentially do that with a create helper.
+ JWL: It doesn’t matter how you do it, you need an example people can follow.

Some discussion of how it might be done: by constructing a new map or by using ~map:put~.

Proposal: accept this PR.

Accepted.

** PR #2134: 1996 Lookups, KeySpecifier: Literal, ContextValueRef
:PROPERTIES:
:CUSTOM_ID: pr-2134
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2134][#2134]]

CG introduces the PR.

+ CG: In the old version a ~KeySpecifier~ had a few specific productions on the RHS.
+ CG: I generalized literals and added ~VarRef~.
+ MK: I have slight reservations about the use of ~.~. People might feel like
  ~?~ is very similar to ~/~ and ~/.~ would do something quite different.
+ CG: You can use variables and in my mind is that ~.~ is like that.
+ MK: Well, yes, but it changes implicitly in places.

Proposal: accept this PR.

Accepted.

** PR #2133: 2132 error handling in logical expressions
:PROPERTIES:
:CUSTOM_ID: pr-2133
:END:
See PR [[https://qt4cg.org/dashboard/#pr-2133][#2133]]

+ MK: I think this is a simple bug fix. We made the statement that with ~and~
  and ~or~ expressions that an error in the second operand is masked. We failed
  to carry that into the spec where we discuss those expressions.
+ RD: Don’t the tables make the paragraph that defines the semantic redundant?
+ MK: Yes, but I think it’s still valuable.

Proposal: accept this PR.

Accepted.

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:END:

None heard.

* Adjourned
:PROPERTIES:
:CUSTOM_ID: adjourned
:END:
