<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version="3.0"
                expand-text="yes">
  <xsl:import href="../../../style/xsl-query-2016.xsl"/>

  <xsl:param name="additional.css" select="'xslt-xquery-serialization-40.css'"/>
  
  <xsl:template match="elcode">
    <a href="../../xslt-40/Overview.html#{.}">{.}</a>
  </xsl:template>

<!-- ==================================================================== -->

<!-- changed templates to auto generate an appendix with a list
     of links to open issues. -->
<xsl:template name="autogenerated-appendices-toc"/>

<xsl:template name="autogenerated-appendices"/>

  <xsl:template match="processing-instruction('schema-for-params')">
    <pre>
      <xsl:sequence
         select="unparsed-text('../src/schema-for-serialization-parameters.xsd')"/>
    </pre>
  </xsl:template>

</xsl:stylesheet>
