<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version="1.0">
  <xsl:import href="../../../style/xsl-query-2016.xsl"/>

  <!-- Baseline date from which differences will be shown -->
  <xsl:param name="diff.baseline" select="'0001-01-01'"/>

<xsl:param name="additional.css" select="'xslt-xquery-serialization-40.css'"/>

<!-- ==================================================================== -->

<!-- changed templates to auto generate an appendix with a list
     of links to open issues. -->
<xsl:template name="autogenerated-appendices-toc"/>

<xsl:template name="autogenerated-appendices"/>

  <xsl:template match="processing-instruction('schema-for-params')">
    <pre>
      <xsl:sequence
         select="unparsed-text('../src/schema-for-serialization-parameters.xsd')"/>
    </pre>
  </xsl:template>

</xsl:stylesheet>

