:PROPERTIES:
:ID:       01798703-6BFD-45F5-B243-E47CF4660537
:END:
#+title: QT4 CG Meeting 065 Agenda 2024-02-13
#+author: Norm Tovey-Walsh
#+filetags: :qt4cg:
#+options: html-style:nil h:6 toc:nil
#+html_head: <link rel="stylesheet" type="text/css" href="/meeting/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
#+html_head: <link rel="shortcut icon" href="/img/QT4-64.png" />
#+html_head: <link rel="apple-touch-icon" sizes="64x64" href="/img/QT4-64.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="76x76" href="/img/QT4-76.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="120x120" href="/img/QT4-120.png" type="image/png" />
#+html_head: <link rel="apple-touch-icon" sizes="152x152" href="/img/QT4-152.png" type="image/png" />
#+options: author:nil email:nil creator:nil timestamp:nil
#+startup: showall

[[../][Agenda index]] / [[https://qt4cg.org][QT4CG.org]] / [[https://qt4cg.org/dashboard][Dashboard]] / [[https://github.com/qt4cg/qtspecs/issues][GH Issues]] / [[https://github.com/qt4cg/qtspecs/pulls][GH Pull Requests]]

* Agenda
:PROPERTIES:
:unnumbered: t
:CUSTOM_ID: agenda
:END:

This meeting will be hosted on Zoom at 16:00BST (17:00CEST, 11:00EDT, 08:00PDT).

See the [[https://qt4cg.org/meeting/logistics.html][meeting logistics]] page for details.

* Administrivia
:PROPERTIES:
:CUSTOM_ID: administrivia
:END:

** Roll call
:PROPERTIES:
:CUSTOM_ID: roll-call
:END:

** Approve the agenda
:PROPERTIES:
:CUSTOM_ID: accept-agenda
:END:

** Approve minutes of previous meeting
:PROPERTIES:
:CUSTOM_ID: approve-minutes
:END:

Minutes of [[../../minutes/2024/02-06.html][the previous meeting]].

** Next meeting
:PROPERTIES:
:CUSTOM_ID: next-meeting
:END:

This meeting is planned for 13 February. The following meeting is
scheduled for 20 February.

Any regrets for 20 February 2024?

** Review of open action items [0/7]
:PROPERTIES:
:CUSTOM_ID: open-actions
:END:

(Items marked [X] are believed to have been closed via email before
this agenda was posted.)

+ [ ] QT4CG-052-02: NW to consider how to schedule an “editor’s meeting”
+ [ ] QT4CG-056-04: MK to write a proposal for adding a select attribute to xsl:text
+ [ ] QT4CG-058-02: MK to consider providing more advice about the pitfalls of mixing decimal and double when sorting
+ [ ] QT4CG-062-03: JK to revise the fn:hash function along the lines discussed at the meeting
+ [ ] QT4CG-063-01: MK to revise #956 especially with respect to the options parameter
+ [ ] QT4CG-063-02: JK to consider whether the roman numeral example is appropriate for the spec.
+ [ ] QT4CG-063-03: DN to address the editorial remarks from meeting 063 in a new PR.
+ [ ] QT4CG-063-04: NW to try to add test review to the editorial meeting.
+ [ ] QT4CG-063-05: MK to revise PR #953 to take account of CG’s comments
+ [ ] QT4CG-063-06: MK to consider refactoring the declare item type syntax to something like declare record
+ [ ] QT4CG-064-01: MK to remove “#…” and “#x…” arguments from ~fn:char~
+ [ ] QT4CG-064-02: CG to update the fallback function to use the new ~char~ argument.
+ [ ] QT4CG-064-03: CG to add examples to show how JSON parsing changes are useful.
+ [ ] QT4CG-064-04: CG to change the return type of ~fallback~ to ~xs:untypedAtomic?~
+ [ ] QT4CG-064-05: CG to amend the names in the keys-where example to be more inclusive
+ [ ] QT4CG-064-06: Add a ~keys-where~ example that uses the value in a more interesting way.
+ [ ] QT4CG-064-07: CG to add an ~array:index-of~ example that uses a collation
+ [ ] QT4CG-064-08: NW to open an issue to try to resolve $search to $target consistently.

** Review of open pull requests and issues
:PROPERTIES:
:CUSTOM_ID: open-pull-requests
:END:

T.B.A.

* Technical Agenda
:PROPERTIES:
:CUSTOM_ID: technical-agenda
:END:


** PR #795: 655 fn:sort-with
:PROPERTIES:
:CUSTOM_ID: pr-795
:END:
See PR [[https://qt4cg.org/dashboard/#pr-795][#795]]

T.B.D. Was there progress over the week or is more discussion required?

** PR #972: 949 Partial Function Applications: Allow return of function name
:PROPERTIES:
:CUSTOM_ID: pr-972
:END:
See PR [[https://qt4cg.org/dashboard/#pr-972][#972]]

** PR #988: 960 Pinned and labeled values
:PROPERTIES:
:CUSTOM_ID: pr-988
:END:
See PR [[https://qt4cg.org/dashboard/#pr-988][#988]]

** PR #985: 720 Add lookup arrow expressions (method invocations)
:PROPERTIES:
:CUSTOM_ID: pr-985
:END:
See PR [[https://qt4cg.org/dashboard/#pr-985][#985]]

** PR #978: 948 Reflected the comments of the CG on the specification of scan-left and scan-right
:PROPERTIES:
:CUSTOM_ID: pr-978
:END:
See PR [[https://qt4cg.org/dashboard/#pr-978][#978]]

** PR #953: 617 Define record constructors
:PROPERTIES:
:CUSTOM_ID: pr-953
:END:
See PR [[https://qt4cg.org/dashboard/#pr-953][#953]]

** PR #916: 720 Allow methods in maps with access to $this
:PROPERTIES:
:CUSTOM_ID: pr-916
:END:
See PR [[https://qt4cg.org/dashboard/#pr-916][#916]]

** PR #832: 77 Add map:deep-update and array:deep-update
:PROPERTIES:
:CUSTOM_ID: pr-832
:END:
See PR [[https://qt4cg.org/dashboard/#pr-832][#832]]

* Any other business
:PROPERTIES:
:CUSTOM_ID: any-other-business
:END:





