name: Remove Label "Propose Closing" on Reopen

on:
  issues:
    types: [reopened]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
    - name: Remove "Propose Closing with No Action" label if it exists
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: "Propose Closing with No Action"
